package com.lxzl.erp.common.constant;

import java.util.HashMap;
import java.util.Map;

public class ErrorCode {
    private static Map<String, String> MAP = new HashMap<String, String>();
    /**
     * 返回码
     */
    public static final String SUCCESS = "J000000";
    public static final String SYSTEM_DEVELOPING = "J000001";
    public static final String EMAIL_ERROR = "J000002";
    public static final String DATA_NOT_BELONG_TO_YOU = "J000003";
    public static final String DATA_HAVE_NO_PERMISSION = "J000004";
    public static final String START_TIME_NOT_NULL = "J000989";
    public static final String END_TIME_NOT_NULL = "J000990";
    public static final String COMMITTED_CAN_NOT_REPEAT = "J000991";
    public static final String COMMIT_ONLY_SELF = "J000992";
    public static final String RECORD_USED_CAN_NOT_DELETE = "J000993";
    public static final String AMOUNT_MAST_MORE_THEN_ZERO = "J000994";
    public static final String USER_NOT_LOGIN = "J000995";
    public static final String CUSTOM_ERROR = "J000996";
    public static final String BUSINESS_EXCEPTION = "J000997";
    public static final String SYSTEM_EXCEPTION = "J000998";
    public static final String SYSTEM_ERROR = "J000999";
    public static final String RECORD_NOT_EXISTS = "J009999";
    public static final String RECORD_ALREADY_EXISTS = "J099999";

    public static final String USER_NAME_NOT_NULL = "J100000";
    public static final String USER_PASSWORD_NOT_NULL = "J100001";
    public static final String USER_DISABLE = "J100002";
    public static final String USER_NOT_ACTIVATED = "J100003";
    public static final String USER_NAME_NOT_FOUND = "J100004";
    public static final String USER_PASSWORD_ERROR = "J100005";
    public static final String USER_EXISTS = "J100006";
    public static final String USER_NOT_EXISTS = "J100007";
    public static final String USER_ROLE_NOT_NULL = "J100008";
    public static final String ROLE_NOT_NULL = "J100009";
    public static final String ROLE_HAVE_USER = "J100010";
    public static final String ROLE_NAME_NOT_NULL = "J100011";
    public static final String ROLE_ID_NOT_NULL = "J100013";
    public static final String DEPARTMENT_ID_NOT_NULL = "J100014";
    public static final String DEPARTMENT_NOT_NULL = "J100015";
    public static final String USER_NOT_NULL = "J100016";
    public static final String ACTIVE_USER_ID_NOT_NULL = "J100017";
    public static final String SUB_COMPANY_NAME_NOT_NULL = "J100018";
    public static final String DEPARTMENT_NOT_EXISTS = "J100019";
    public static final String USER_PASSWORD_TOO_SIMPLE = "J100020";
    public static final String USER_OLD_PASSWORD_NOT_NULL = "J100021";
    public static final String USER_NEW_PASSWORD_NOT_NULL = "J100022";
    public static final String USER_OWNER_NOT_EXISTS = "J100023";
    public static final String USER_UNION_NOT_EXISTS = "J100024";
    public static final String PHONE_ERROR = "J100025";
    public static final String BUSINESS_APP_ID_NOT_NULL = "J100026";
    public static final String BUSINESS_APP_SECRET_NOT_NULL = "J100027";
    public static final String BUSINESS_SYSTEM_ERROR = "J100028";

    public static final String PRODUCT_ID_NOT_NULL = "J200000";
    public static final String PRODUCT_NAME_NOT_NULL = "J200001";
    public static final String PRODUCT_PROPERTY_NOT_NULL = "J200002";
    public static final String PRODUCT_SKU_NOT_NULL = "J200003";
    public static final String PRODUCT_SKU_PROPERTY_NOT_NULL = "J200004";
    public static final String PRODUCT_PROPERTY_VALUE_NOT_NULL = "J200005";
    public static final String PRODUCT_SKU_PROPERTY_VALUE_NOT_NULL = "J200006";
    public static final String PRODUCT_IMAGE_UPLOAD_ERROR = "J200007";
    public static final String PRODUCT_IS_NULL_OR_NOT_EXISTS = "J200008";
    public static final String PRODUCT_SKU_IS_NULL_OR_NOT_EXISTS = "J200009";
    public static final String PRODUCT_SKU_PRICE_ERROR = "J200010";
    public static final String PRODUCT_SKU_COUNT_ERROR = "J200011";
    public static final String PRODUCT_CATEGORY_PROPERTY_NOT_EXISTS = "J200012";
    public static final String PRODUCT_CATEGORY_PROPERTY_VALUE_NOT_EXISTS = "J200013";
    public static final String PRODUCT_CATEGORY_PROPERTY_VALUE_ALREADY_EXISTS = "J200014";
    public static final String PRODUCT_EQUIPMENT_NOT_EXISTS = "J200015";
    public static final String MATERIAL_NOT_EXISTS = "J200016";
    public static final String PRODUCT_EQUIPMENT_HAVE_NO_BULK_MATERIAL = "J200017";
    public static final String PRODUCT_EQUIPMENT_IS_NOT_IDLE = "J200018";
    public static final String BULK_MATERIAL_IS_IN_PRODUCT_EQUIPMENT = "J200019";
    public static final String BULK_MATERIAL_NOT_EXISTS = "J200020";
    public static final String PRODUCT_NOT_EXISTS = "J200021";
    public static final String PRODUCT_EQUIPMENT_NOT_IN_THIS_WAREHOUSE = "J200022";
    public static final String PRODUCT_IS_NOT_RENT = "J200023";
    public static final String MATERIAL_IN_USED = "J200024";
    public static final String PRODUCT_SKU_CAN_NOT_DELETE = "J200025";
    public static final String BULK_MATERIAL_IS_NOT_IDLE = "J200026";
    public static final String BULK_MATERIAL_STATUS_ERROR = "J200027";
    public static final String PRODUCT_EQUIPMENT_STATUS_ERROR = "J200028";
    public static final String BULK_MATERIAL_NOT_IN_THIS_WAREHOUSE = "J200029";
    public static final String PRODUCT_MATERIAL_NOT_MATCHING = "J200030";
    public static final String PRODUCT_MATERIAL_MEMORY_NOT_MATCHING = "J200031";
    public static final String PRODUCT_MATERIAL_MAIN_BOARD_NOT_MATCHING = "J200032";
    public static final String PRODUCT_MATERIAL_CPU_NOT_MATCHING = "J200033";
    public static final String PRODUCT_MATERIAL_HDD_NOT_MATCHING = "J200034";
    public static final String PRODUCT_MATERIAL_GRAPHICS_CARD_NOT_MATCHING = "J200035";
    public static final String PRODUCT_MATERIAL_POWER_SUPPLY_NOT_MATCHING = "J200036";
    public static final String PRODUCT_MATERIAL_RADIATOR_NOT_MATCHING = "J200037";
    public static final String PRODUCT_MATERIAL_SSD_NOT_MATCHING = "J200038";
    public static final String PRODUCT_MATERIAL_BOX_NOT_MATCHING = "J200039";
    public static final String PRODUCT_EQUIPMENT_IS_NOT_BUSY = "J200040";
    public static final String BULK_MATERIAL_IS_NOT_BUSY = "J200041";
    public static final String BULK_MATERIAL_IS_IN_ORDER_EQUIPMENT = "J200042";
    public static final String BULK_MATERIAL_HAVE_NOT_ENOUGH = "J200043";
    public static final String BULK_MATERIAL_ID_NOT_NULL = "J200044";
    public static final String PRODUCT_EQUIPMENT_MATERIAL_COUNT_NOT_ENOUGH = "J200045";
    public static final String PRODUCT_EQUIPMENT_BULK_MATERIAL_NOT_EXISTS = "J200046";
    public static final String CURRENT_EQUIPMENT_ID_NOT_NULL = "J200047";
    public static final String CURRENT_EQUIPMENT_NO_NOT_NULL = "J200048";
    public static final String PRODUCT_EQUIPMENT_MATERIAL_NOT_EXISTS = "J200049";
    public static final String BULK_MATERIAL_IS_IN_PRODUCT_EQUIPMENT_NOT_REPAIR = "J200050";
    public static final String BULK_MATERIAL_IS_NOT_IN_PRODUCT_EQUIPMENT = "J200051";
    public static final String INSTALL_AND_DISMANTLE_WAREHOUSE_NOT_EQUAL = "J200052";
    public static final String BULK_MATERIAL_IS_NULL = "J200053";
    public static final String PRODUCT_EQUIPMENT_IS_NULL = "J200054";
    public static final String PRODUCT_EQUIPMENT_MATERIAL_IS_NULL = "J200055";
    public static final String BULK_MATERIAL_NO_NOT_NULL = "J200056";
    public static final String PRODUCT_EQUIPMENT_NOT_SAME_WAREHOUSE = "J200057";
    public static final String BULK_MATERIAL_NOT_SAME_WAREHOUSE = "J200058";
    public static final String PRODUCT_EQUIPMENT_AND_BULK_MATERIAL_NOT_SAME_WAREHOUSE = "J200059";
    public static final String PRODUCT_EQUIPMENT_STATUS_NOT_REPAIR = "J200060";
    public static final String BULK_MATERIAL_STATUS_NOT_REPAIR = "J200061";
    public static final String PRODUCT_NOT_SAME = "J200062";
    public static final String MATERIAL_NOT_SAME = "J200063";
    public static final String CUSTOMER_COMPANY_NEED_SKU_ID_NOT_NULL = "J200064";
    public static final String CUSTOMER_COMPANY_NEED_UNIT_PRICE_NOT_NULL = "J200065";
    public static final String CUSTOMER_COMPANY_NEED_RENT_COUNT_NOT_NULL = "J200066";
    public static final String CUSTOMER_COMPANY_NEED_RENT_LENGHT_NOT_NULL = "J200067";
    public static final String CUSTOMER_COMPANY_NEED_FIRST_NOT_NULL = "J200068";
    public static final String WAREHOUSE_NOT_AVAILABLE = "J200069";
    public static final String PRODUCT_EQUIPMENT_NOT_NEW = "J200070";
    public static final String PRODUCT_EQUIPMENT_NOT_OLD = "J200071";
    public static final String PRODUCT_NEW_SKU_PRICE_IS_NOT_NULL = "J200072";
    public static final String PRODUCT_NEW_DAY_RENT_PRICE_IS_NOT_NULL = "J200073";
    public static final String PRODUCT_NEW_MONTH_RENT_PRICE_IS_NOT_NULL = "J200074";
    public static final String BUYER_CUSTOMER_NO_NOT_NULL = "J200075";


    public static final String WORKFLOW_TYPE_NOT_EXISTS = "J800001";
    public static final String WORKFLOW_TEMPLATE_HAVE_NO_NODE = "J800002";
    public static final String WORKFLOW_LINK_EXISTS = "J800003";
    public static final String WORKFLOW_LINK_NOT_EXISTS = "J800004";
    public static final String WORKFLOW_LINK_HAVE_NO_DETAIL = "J800005";
    public static final String WORKFLOW_LINK_VERIFY_ALREADY_OVER = "J800006";
    public static final String WORKFLOW_NOT_BELONG_TO_YOU = "J800007";
    public static final String WORKFLOW_NOT_EXISTS_CLOSED = "J800008";
    public static final String WORKFLOW_NODE_NOT_EXISTS = "J800009";
    public static final String WORKFLOW_VERIFY_USER_ERROR = "J800010";
    public static final String WORKFLOW_LINK_STATUS_ERROR = "J800011";
    public static final String WORKFLOW_TEMPLATE_NOT_EXISTS = "J800012";
    public static final String WORKFLOW_HAVE_NO_CONFIG = "J800013";

    public static final String REMARK_PATTERN = "J900001";
    public static final String ID_NOT_NULL = "J900002";
    public static final String MONEY_MORE_THAN_ZERO = "J900003";
    public static final String IMAGE_NOT_EXISTS = "J900004";
    public static final String IMAGE_TYPE_ERROR = "J900005";
    public static final String IMAGE_USED = "J900006";
    public static final String DATA_DICTIONARY_NAME_NOT_NULL = "J900007";
    public static final String PARAM_IS_NOT_NULL = "J900008";
    public static final String HAVE_NO_CHANGE_STATUS = "J900009";
    public static final String STATUS_PATTERN = "J900010";
    public static final String COUNT_MORE_THAN_ZERO = "J900011";
    public static final String DAYS_MORE_THAN_ZERO = "J900012";
    public static final String DATA_STATUS_ERROR = "J900013";
    public static final String VERIFY_STATUS_ERROR = "J900014";
    public static final String OPERATOR_IS_NOT_YOURSELF = "J900015";
    public static final String PARAM_IS_NOT_ENOUGH = "J900016";
    public static final String NO_DUPLICATE_COMMIT = "J900017";
    public static final String PARAM_IS_ERROR = "J900018";

    public static final String PURCHASE_ORDER_ID_NOT_NULL = "J300000";
    public static final String PRODUCT_SUPPLIER_ID_NOT_NULL = "J300001";
    public static final String WAREHOUSE_ID_NOT_NULL = "J300002";
    public static final String IS_INVOICE_NOT_NULL = "J300003";
    public static final String IS_NEW_NOT_NULL = "J300004";
    public static final String PURCHASE_ORDER_PRODUCT_LIST_NOT_NULL = "J300005";
    public static final String IS_INVOICE_VALUE_ERROR = "J300006";
    public static final String IS_NEW_VALUE_ERROR = "J300007";
    public static final String PURCHASE_ORDER_NO_NOT_NULL = "J300008";
    public static final String PURCHASE_ORDER_NOT_EXISTS = "J300009";
    public static final String PURCHASE_ORDER_COMMITTED_CAN_NOT_UPDATE = "J300010";
    public static final String PURCHASE_ORDER_CANNOT_CREATE_BY_NEW_AND_AMOUNT = "J300011";
    public static final String WAREHOUSE_NOT_EXISTS = "J300012";
    public static final String PURCHASE_ORDER_PRODUCT_CAN_NOT_REPEAT = "J300013";
    public static final String PURCHASE_ORDER_COMMITTED_CAN_NOT_COMMIT_AGAIN = "J300014";
    public static final String WAREHOUSE_IN_STORAGE_LIST_NOT_NULL = "J300015";
    public static final String USER_CAN_NOT_OP_WAREHOUSE = "J300016";
    public static final String VERIFY_USER_NOT_NULL = "J300017";
    public static final String PURCHASE_ORDER_COMMITTED_CAN_NOT_CANCEL = "J300018";
    public static final String PURCHASE_DELIVERY_ORDER_NO_NOT_NULL = "J300019";
    public static final String PURCHASE_DELIVERY_ORDER_NOT_EXISTS = "J300020";
    public static final String WAREHOUSE_NO_NOT_NULL = "J300021";
    public static final String SUPPLIER_NOT_EXISTS = "J300022";
    public static final String PURCHASE_RECEIVE_ORDER_NO_NOT_NULL = "J300023";
    public static final String PURCHASE_RECEIVE_ORDER_NOT_EXISTS = "J300024";
    public static final String PURCHASE_RECEIVE_ORDER_AUTO_ALLOT_YES_CAN_NOT_UPDATE = "J300025";
    public static final String PURCHASE_RECEIVE_ORDER_STATUS_CAN_NOT_UPDATE = "J300026";
    public static final String PURCHASE_RECEIVE_ORDER_PRODUCT_LIST_NOT_NULL = "J300027";
    public static final String PURCHASE_RECEIVE_ORDER_PRODUCT_REAL_COUNT_NOT_NULL = "J300028";
    public static final String PURCHASE_RECEIVE_ORDER_PRODUCT_SKU_ID_NOT_NULL = "J300029";
    public static final String STOCK_ORDER_ALREADY_EXISTS = "J300030";
    public static final String PURCHASE_ORDER_STATUS_CAN_NOT_END = "J300031";
    public static final String PURCHASE_ORDER_STATUS_CAN_NOT_CONTINUE = "J300032";
    public static final String PURCHASE_RECEIVE_ORDER_STATUS_YET_CAN_NOT_IN_AGAIN = "J300033";
    public static final String PURCHASE_TYPE_ERROR = "J300034";
    public static final String PURCHASE_TYPE_NOT_NULL = "J300035";
    public static final String PURCHASE_PRODUCT_MATERIAL_CAN_NOT_ALL_NULL = "J300036";
    public static final String MATERIAL_ID_NOT_NULL = "J300037";
    public static final String MATERIAL_PRICE_ERROR = "J300038";
    public static final String MATERIAL_COUNT_ERROR = "J300039";
    public static final String PURCHASE_ORDER_SKU_MATERIAL_ERROR = "J300040";
    public static final String PURCHASE_ORDER_MATERIAL_CAN_NOT_REPEAT = "J300041";
    public static final String PURCHASE_ORDER_MATERIAL_NOT_MAIN = "J300042";
    public static final String PURCHASE_ORDER_MATERIAL_NOT_GADGET = "J300043";
    public static final String PURCHASE_ORDER_MATERIAL_LIST_NOT_NULL = "J300044";
    public static final String PURCHASE_ORDER_MATERIAL_CAN_NOT_CREATE = "J300045";
    public static final String MATERIAL_NO_NOT_NULL = "J300046";
    public static final String STOCK_ALLOCATION_WAREHOUSE_IS_NOT_SAME = "J300047";
    public static final String WAREHOUSE_OUT_STORAGE_LIST_NOT_NULL = "J300048";
    public static final String PURCHASE_RECEIVE_ORDER_MATERIAL_ID_NOT_NULL = "J300049";
    public static final String PURCHASE_RECEIVE_ORDER_MATERIAL_REAL_COUNT_NOT_NULL = "J300050";
    public static final String MATERIAL_CAPACITY_VALUE_NOT_NULL = "J300051";
    public static final String MATERIAL_MODEL_NOT_NULL = "J300052";
    public static final String MATERIAL_TYPE_HAVE_NO_MODEL = "J300053";
    public static final String PURCHASE_RECEIVE_ORDER_MATERIAL_NO_NOT_NULL = "J300054";
    public static final String STOCK_NOT_MATCH = "J300055";
    public static final String STOCK_NOT_ENOUGH = "J300056";
    public static final String EQUIPMENT_PURCHASE_PRICE_NOT_NULL = "J300057";
    public static final String BULK_PURCHASE_PRICE_NOT_NULL = "J300058";
    public static final String PURCHASE_RECEIVE_ORDER_STATUS_YET_CAN_NOT_COMMIT = "J300059";
    public static final String SUB_COMPANY_NOT_EXISTS = "J300060";
    public static final String PURCHASE_TAX_RATE_ERROR = "J300061";
    public static final String SUPPLIER_IS_EXISTS = "J300062";
    public static final String MUST_HAVE_MAIN = "J300063";
    public static final String SUPPLIER_NAME_NOT_NULL = "J300064";
    public static final String SUPPLIER_CODE_NOT_CN= "J300065";
    public static final String BENEFICIARY_BANK_NAME_IS_LENGTH = "J300066";
    public static final String BENEFICIARY_NAME_IS_LENGTH = "J300067";
    public static final String BENEFICIARY_ACCOUNT_IS_MATH = "J300068";
    public static final String SUPPLIER_CODE_IS_EXISTS = "J300069";
    public static final String SUPPLIER_NAME_IS_NULL = "J300070";
    public static final String BENEFICIARY_ACCOUNT_IS_LENGTH = "J300071";
    public static final String SUPPLIER_CODE_IS_LENGTH= "J300072";

    public static final String ORDER_PRODUCT_LIST_NOT_NULL = "J400000";
    public static final String ORDER_CUSTOMER_CONSIGN_NOT_NULL = "J400001";
    public static final String ORDER_PRODUCT_STOCK_NEW_INSUFFICIENT = "J400002";
    public static final String ORDER_PRODUCT_STOCK_OLD_INSUFFICIENT = "J400003";
    public static final String ORDER_NOT_EXISTS = "J400004";
    public static final String ORDER_PRODUCT_EQUIPMENT_NOT_NULL = "J400005";
    public static final String ORDER_PRODUCT_EQUIPMENT_STATUS_ERROR = "J400006";
    public static final String ORDER_PRODUCT_EQUIPMENT_SKU_NOT_SAME = "J400007";
    public static final String ORDER_PRODUCT_EQUIPMENT_IS_NULL = "J400008";
    public static final String ORDER_STATUS_ERROR = "J400009";
    public static final String ORDER_PRODUCT_EQUIPMENT_COUNT_ERROR = "J400010";
    public static final String ORDER_RENT_TYPE_OR_LENGTH_ERROR = "J400011";
    public static final String ORDER_PAY_MODE_NOT_NULL = "J400012";
    public static final String ORDER_PAY_STATUS_ERROR = "J400013";
    public static final String ORDER_REFUND_STATUS_ERROR = "J400014";
    public static final String ORDER_PAY_RECORD_NOT_EXISTS = "J400015";
    public static final String ORDER_PRODUCT_BULK_MATERIAL_COUNT_ERROR = "J400016";
    public static final String ORDER_HAVE_NO_RENT_START_TIME = "J400017";
    public static final String ORDER_STATUS_NOT_PROCESSED = "J400018";
    public static final String ORDER_PRODUCT_AMOUNT_ERROR = "J400019";
    public static final String ORDER_MATERIAL_AMOUNT_ERROR = "J400020";
    public static final String ORDER_HAVE_NO_THIS_ITEM = "J400021";
    public static final String ORDER_PRODUCT_EQUIPMENT_COUNT_MAX = "J400022";
    public static final String ORDER_MATERIAL_BULK_COUNT_MAX = "J400023";
    public static final String DEPLOYMENT_ORDER_PRODUCT_EQUIPMENT_STOCK_NOT_ENOUGH = "J400024";
    public static final String DEPLOYMENT_ORDER_BULK_MATERIAL_STOCK_NOT_ENOUGH = "J400025";
    public static final String DEPLOYMENT_ORDER_STATUS_ERROR = "J400026";
    public static final String DEPLOYMENT_ORDER_HAVE_NO_THIS_ITEM = "J400027";
    public static final String RETURN_ORDER_NO_NOT_NULL = "J400028";
    public static final String EQUIPMENT_NO_NOT_NULL = "J400029";
    public static final String RETURN_ORDER_NOT_EXISTS = "J400030";
    public static final String EQUIPMENT_NOT_EXISTS = "J400031";
    public static final String EQUIPMENT_NOT_RENT = "J400032";
    public static final String DEPLOYMENT_ORDER_PRODUCT_EQUIPMENT_COUNT_MAX = "J400033";
    public static final String DEPLOYMENT_ORDER_MATERIAL_BULK_COUNT_MAX = "J400034";
    public static final String DEPLOYMENT_ORDER_WAREHOUSE_NOT_SAME = "J400035";
    public static final String DEPLOYMENT_ORDER_HAVE_LOCK_ITEM = "J400036";
    public static final String DEPLOYMENT_ORDER_PRODUCT_EQUIPMENT_COUNT_NOT_ENOUGH = "J400037";
    public static final String DEPLOYMENT_ORDER_MATERIAL_BULK_COUNT_NOT_ENOUGH = "J400038";
    public static final String RETURN_ORDER_STATUS_CAN_NOT_END = "J400039";
    public static final String RETURN_ORDER_STATUS_CAN_NOT_CANCEL = "J400040";
    public static final String RETURN_ORDER_STATUS_CAN_NOT_RETURN = "J400041";
    public static final String RETURN_ORDER_PRODUCT_ID_NOT_NULL = "J400042";
    public static final String RETURN_ORDER_MATERIAL_ID_NOT_NULL = "J400043";
    public static final String RETURN_ORDER_SERVICE_COST_NOT_NULL = "J400044";
    public static final String RETURN_ORDER_SERVICE_COST_ERROR = "J400045";
    public static final String RETURN_ORDER_DAMAGE_COST_NOT_NULL = "J400046";
    public static final String RETURN_ORDER_DAMAGE_COST_ERROR = "J400047";
    public static final String ORDER_HAVE_NO_PAID = "J400048";
    public static final String ORDER_CAN_NOT_DELIVERY = "J400049";
    public static final String ORDER_PAY_MODE_ERROR = "J400050";
    public static final String RETURN_ORDER_IS_CHARGING_IS_NOT_NULL = "J400051";
    public static final String CHANGE_COUNT_ERROR = "J400052";
    public static final String RETURN_COUNT_ERROR = "J400053";
    public static final String CHANGE_ORDER_NO_NOT_NULL = "J400054";
    public static final String CHANGE_ORDER_NOT_EXISTS = "J400055";
    public static final String CHANGE_ORDER_COMMITTED_CAN_NOT_COMMIT_AGAIN = "J400056";
    public static final String CHANGE_ORDER_STATUS_CAN_NOT_STOCK_UP = "J400057";
    public static final String CHANGE_ORDER_CAN_NOT_UPDATE = "J400058";
    public static final String CHANGE_ORDER_PRODUCT_ID_NOT_NULL = "J400059";
    public static final String CHANGE_ORDER_MATERIAL_ID_NOT_NULL = "J400060";
    public static final String CHANGE_ORDER_STATUS_CAN_NOT_DELIVERY = "J400061";
    public static final String CHANGE_ORDER_STATUS_CAN_NOT_END = "J400062";
    public static final String ORDER_PRODUCT_EQUIPMENT_NOT_EXISTS = "J400063";
    public static final String ORDER_PRODUCT_EQUIPMENT_ALREADY_RETURN = "J400064";
    public static final String CHANGE_ORDER_STATUS_CAN_NOT_CANCEL = "J400065";
    public static final String CHANGE_ORDER_STATUS_CAN_NOT_DO_CHANGE = "J400066";
    public static final String CHANGE_ONLY_SAME_SKU = "J400067";
    public static final String ORDER_ALREADY_PAID = "J400068";
    public static final String ORDER_MATERIAL_BULK_NOT_EXISTS = "J400069";
    public static final String ORDER_MATERIAL_BULK_ALREADY_RETURN = "J400070";
    public static final String CHANGE_ORDER_SRC_EQUIPMENT_NO_NOT_NULL = "J400071";
    public static final String CHANGE_ORDER_CAN_NOT_CHANGE = "J400072";
    public static final String CHANGE_ORDER_SRC_MATERIAL_NO_NOT_NULL = "J400073";
    public static final String CHANGE_ORDER_MATERIAL_CAN_NOT_MODIFY = "J400074";
    public static final String CHANGE_ORDER_NOT_END = "J400075";
    public static final String ORDER_PRODUCT_LIST_REPEAT = "J400076";
    public static final String ORDER_MATERIAL_STOCK_INSUFFICIENT = "J400077";
    public static final String ORDER_MATERIAL_LIST_REPEAT = "J400078";
    public static final String RETURN_OR_CHANGE_MODE_NOT_NULL = "J400079";
    public static final String RETURN_OR_CHANGE_MODE_ERROR = "J400080";
    public static final String RETURN_ORDER_CAN_NOT_UPDATE = "J400081";
    public static final String IS_DAMAGE_NOT_NULL = "J400082";
    public static final String IS_DAMAGE_ERROR = "J400083";
    public static final String RETURN_ORDER_CAN_NOT_COMMIT = "J400084";
    public static final String ORDER_PRODUCT_NOT_EXISTS = "J400085";
    public static final String ORDER_MATERIAL_NOT_EXISTS = "J400086";
    public static final String ORDER_PRODUCT_DEPOSIT_ERROR = "J400087";
    public static final String ORDER_MATERIAL_DEPOSIT_ERROR = "J400088";
    public static final String ORDER_DELIVERY_MODE_ERROR = "J400089";
    public static final String ORDER_CAN_NOT_DELIVERY_TIME_REASON = "J400090";
    public static final String ORDER_MATERIAL_STOCK_NEW_INSUFFICIENT = "J400091";
    public static final String ORDER_MATERIAL_STOCK_OLD_INSUFFICIENT = "J400092";
    public static final String ORDER_PRODUCT_COUNT_ERROR = "J400093";
    public static final String ORDER_MATERIAL_COUNT_ERROR = "J400094";
    public static final String ORDER_PRODUCT_EQUIPMENT_NOT_MATCHING = "J400095";
    public static final String DEPLOYMENT_ORDER_HAVE_NO_THIS_PRODUCT_EQUIPMENT = "J400096";
    public static final String DEPLOYMENT_ORDER_BULK_MATERIAL_NOT_ENOUGH = "J400097";
    public static final String DEPLOYMENT_ORDER_NOT_EXISTS = "J400098";
    public static final String DEPLOYMENT_ORDER_PRODUCT_EQUIPMENT_HAVE_RETURNED = "J400096";
    public static final String PURCHASE_APPLY_ORDER_NO_NOT_NULL = "J400097";
    public static final String PURCHASE_APPLY_ORDER_NOT_EXISTS = "J400098";
    public static final String BULK_MATERIAL_HAVE_NOT_ENOUGH_BY_PARAM = "J400099";
    public static final String PURCHASE_APPLY_CAN_NOT_UPDATE = "J400100";
    public static final String PURCHASE_APPLY_CAN_NOT_CANCEL_BY_STATUS = "J400101";
    public static final String PURCHASE_APPLY_YET_RECEIVE_CAN_NOT_CANCEL = "J400102";
    public static final String PURCHASE_APPLY_USE_TIME_NOT_NUll = "J400103";
    public static final String PURCHASE_APPLY_CAN_NOT_PAUSE = "J400104";
    public static final String PURCHASE_APPLY_CAN_NOT_CONTINUE = "J400105";
    public static final String PURCHASE_APPLY_CAN_NOT_END = "J400106";
    public static final String PURCHASE_NOT_HAVE_APPLY = "J400107";
    public static final String ORDER_RENT_LENGTH_MORE_THAN_90 = "J400108";
    public static final String BULK_MATERIAL_NOT_IN_THE_WAREHOUSE = "J400109";
    public static final String ORDER_PRODUCT_EQUIPMENT_NEW_NOT_MATCHING = "J400110";
    public static final String RETURN_TIME_NOT_NULL = "J400111";
    public static final String RETURN_REASON_TYPE_NOT_NULL = "J400112";
    public static final String ORDER_EXPECT_DELIVERY_TIME_ERROR = "J400113";
    public static final String ORDER_NO_NOT_NULL = "J400114";

    public static final String CUSTOMER_COMPANY_NOT_NULL = "J500001";
    public static final String CUSTOMER_COMPANY_NAME_NOT_NULL = "J500002";
    public static final String CUSTOMER_PERSON_NOT_NULL = "J500003";
    public static final String CUSTOMER_PERSON_NAME_NOT_NULL = "J500004";
    public static final String CUSTOMER_TYPE_NOT_NULL = "J500005";
    public static final String CUSTOMER_COMPANY_CONNECT_NAME_NOT_NULL = "J500006";
    public static final String CUSTOMER_NOT_NULL = "J500007";
    public static final String CUSTOMER_NO_NOT_NULL = "J500008";
    public static final String CUSTOMER_RISK_MANAGEMENT_ID_NOT_NULL = "J500009";
    public static final String CUSTOMER_RISK_MANAGEMENT_CREDIT_AMOUNT_NOT_NULL = "J500010";
    public static final String CUSTOMER_RISK_MANAGEMENT_DEPOSIT_CYCLE_NOT_NULL = "J500011";
    public static final String CUSTOMER_RISK_MANAGEMENT_PAYMENT_CYCLE_NOT_NULL = "J500012";
    public static final String CUSTOMER_NOT_EXISTS = "J500013";
    public static final String CUSTOMER_RISK_MANAGEMENT_CREDIT_AMOUNT_ERROR = "J500014";
    public static final String CUSTOMER_RISK_MANAGEMENT_DEPOSIT_CYCLE_ERROR = "J500015";
    public static final String CUSTOMER_RISK_MANAGEMENT_PAYMENT_CYCLE_ERROR = "J500016";
    public static final String CUSTOMER_RISK_MANAGEMENT_NOT_EXISTS = "J500017";
    public static final String CUSTOMER_HAVE_NO_RETURN = "J500018";
    public static final String CUSTOMER_NOT_RENT_THIS = "J500019";
    public static final String CUSTOMER_RETURN_TOO_MORE = "J500020";
    public static final String CONSIGNEE_NAME_NOT_NULL = "J500021";
    public static final String CONSIGNEE_PHONE_NOT_NULL = "J500022";
    public static final String PROVINCE_ID_NOT_NULL = "J500023";
    public static final String CITY_ID_NOT_NULL = "J500024";
    public static final String DISTRICT_ID_NOT_NULL = "J500025";
    public static final String ADDRESS_NOT_NULL = "J500026";
    public static final String PRODUCT_SKU_CAN_NOT_REPEAT = "J500029";
    public static final String MATERIAL_CAN_NOT_REPEAT = "J500030";
    public static final String CUSTOMER_CONSIGN_NOT_EXISTS = "J500031";
    public static final String CUSTOMER_GET_CREDIT_AMOUNT_OVER_FLOW = "J500032";
    public static final String CUSTOMER_CONSIGN_INFO_NOT_EXISTS = "J500033";
    public static final String CUSTOMER_CONSIGN_INFO_IS_MAIN_NOT_NULL = "J500034";
    public static final String CUSTOMER_CONSIGN_INFO_IS_MAIN_ERROR = "J500035";
    public static final String CUSTOMER_CONSIGN_INFO_ID_NOT_NULL = "J500036";
    public static final String CUSTOMER_COMPANY_CONNECT_PHONE_NOT_NULL = "J500037";
    public static final String CUSTOMER_COMPANY_ADDRESS_NOT_NULL = "J500038";
    public static final String CUSTOMER_PERSON_PHONE_NOT_NULL = "J500039";
    public static final String CUSTOMER_PERSON_ADDRESS_NOT_NULL = "J500040";
    public static final String STATEMENT_ORDER_CREATE_ERROR = "J500041";
    public static final String STATEMENT_ORDER_STATUS_ERROR = "J500042";
    public static final String MATERIAL_NOT_RENT = "J500043";
    public static final String PURCHASE_PRICE_ERROR = "J500044";
    public static final String PURCHASE_RECEIVE_REMARK_ERROR = "J500045";
    public static final String PURCHASE_RECEIVE_ORDER_MATERIAL_PRICE_NOT_NEED_UPDATE = "J500046";
    public static final String UPDATE_ITEM_COUNT_ERROR = "J500047";
    public static final String COMPANY_ORIGIN_NOT_NULL = "J500048";
    public static final String SALES_MAN_NOT_NULL = "J500049";
    public static final String CUSTOMER_PERSON_CONNECT_PHONE_NOT_NULL = "J500050";
    public static final String PERSON_NAME_NOT_NULL = "J500051";
    public static final String PERSON_NO_NOT_NULL = "J500052";
    public static final String CUSTOMER_PERSON_CONNECT_REAL_NAME_NOT_NULL = "J500053";
    public static final String PRODUCT_PURPOSE_NOT_NULL = "J500054";
    public static final String LIST_FIRST_NEED_PRODUCTS_NOT_NULL = "J500055";
    public static final String CUSTOMER_COMPANY_NEED_FIRST_LIST_NOT_NULL = "J500056";
    public static final String CUSTOMER_IS_EXISTS = "J500057";
    public static final String CUSTOMER_NOT_RENT_OR_ORDER_NOT_CONFIRM = "J500058";
    public static final String CUSTOMER_RENT_THIS_BULK_MATERIAL_NO_MORE = "J500059";
    public static final String CUSTOMER_OWNER_NOT_NULL = "J500060";
    public static final String STATEMENT_ORDER_CAN_NOT_PAID_THIS = "J500061";
    public static final String CUSTOMER_RISK_MANAGEMENT_APPLE_LIMIT = "J500062";
    public static final String CUSTOMER_RISK_MANAGEMENT_NEW_LIMIT = "J500063";
    public static final String CUSTOMER_RISK_MANAGEMENT_PRICE_LIMIT = "J500064";
    public static final String CUSTOMER_STATUS_ERROR = "J500065";
    public static final String CUSTOMER_IS_DISABLED = "J500066";
    public static final String CUSTOMER_CAN_NOT_EDIT = "J500067";
    public static final String CUSTOMER_GET_CREDIT_NEED_RISK_INFO = "J500068";
    public static final String STATEMENT_PAY_TYPE_ERROR = "J500069";
    public static final String STATEMENT_PAY_FAILED = "J500070";
    public static final String STATEMENT_PAY_AMOUNT_DIFF_ERROR = "J500071";
    public static final String SHORT_LIMIT_RECEIVABLE_AMOUNT_NOT_NULL = "J500072";
    public static final String CUSTOMER_OWNER_NOT_CHANGE_ELECTRIC_SALE_COMPANY = "J500073";
    public static final String CUSTOMER_UNION_USER_NOT_CHANGE_ELECTRIC_SALE_COMPANY = "J500074";
    public static final String CUSTOMER_OWNER_IS_NOT_HEADER_COMPANY = "J500075";
    public static final String CUSTOMER_UNION_USER_IS_NOT_HEADER_COMPANY = "J500076";
    public static final String STATEMENT_DATE_NOT_NULL = "J500077";
    public static final String CUSTOMER_OWNER_USER_AND_UNION_USER_NOT_SAME = "J500078";
    public static final String CUSTOMER_IS_DEFAULT_CONSIGN_ADDRESS_NOT_NULL = "J500079";
    public static final String CUSTOMER_CONSIGN_ADDRESS_NOT_NULL = "J500080";
    public static final String CUSTOMER_COMPANY_INDUSTRY_NOT_NULL = "J500081";
    public static final String CUSTOMER_COMPANY_FOUND_TIME_NOT_NULL = "J500082";
    public static final String CUSTOMER_COMPANY_REGISTERED_CAPITAL_NOT_NULL = "J500083";
    public static final String CUSTOMER_COMPANY_OFFICE_NUMBER_NOT_NULL = "J500084";
    public static final String CUSTOMER_COMPANY_OPERATING_AREA_NOT_NULL = "J500085";
    public static final String CUSTOMER_COMPANY_NEED_TOTAL_PRICE_NOT_NULL = "J500086";
    public static final String LEGAL_PERSON_PHONE_EQUAL_TO_AGENT_PERSON_PHONE = "J500087";
    public static final String AGENT_PERSON_PHONE_EQUAL_TO_CONNECT_PHONE = "J500088";
    public static final String CONNECT_PHONE_EQUAL_TO_LEGAL_PERSON_PHONE = "J500089";
    public static final String STATEMENT_ORDER_NO_NOT_NULL = "J500090";
    public static final String STATEMENT_PAY_NOT_NULL = "J500091";
    public static final String OPEN_ID_NOT_NULL = "J500092";
    public static final String CUSTOMER_NAME_NOT_NULL = "J500093";
    public static final String STATEMENT_ORDER_NOT_EXISTS = "J500094";
    public static final String STATEMENT_ORDER_NOT_NULL = "J500095";

    public static final String MESSAGE_TITLE_NOT_NULL = "J600001";
    public static final String MESSAGE_CONTENT_NOT_NULL = "J600002";
    public static final String MESSAGE_RECEIVER_NOT_NULL = "J600003";
    public static final String MESSAGE_ID_NOT_NULL = "J600004";
    public static final String MESSAGE_NOT_EXISTS = "J600005";
    public static final String MESSAGE_CAN_NOT_SEND_SELF = "J600006";

    public static final String EQUIPMENT_AND_BULK_MATERIAL_IS_NOT_NULL = "J700001";
    public static final String REPAIR_REASON_IS_NOT_NULL = "J700002";
    public static final String REPAIR_ORDER_NO_IS_NOT_NULL = "J700003";
    public static final String REPAIR_ORDER_IS_NOT_EXISTS = "J700004";
    public static final String REPAIR_ORDER_STATUS_ERROR = "J700005";
    public static final String REPAIR_ORDER_EQUIPMENT_NOT_EXISTS = "J700006";
    public static final String REPAIR_ORDER_BULK_MATERRIAL_NOT_EXISTS = "J700007";
    public static final String REPAIR_ORDER_DATA_STATUS_ERROR = "J700008";

    public static final String JOINT_PRODUCT_ID_IS_NULL = "J1000001";
    public static final String JOINT_PRODUCT_NAME_IS_NULL = "J1000002";
    public static final String JOINT_PRODUCT_NOT_EXISTS = "J1000003";

    public static final String IMG_ID_NOT_NULL = "J1100001";
    public static final String LEGAL_PERSON_NO_PICTURE_FRONT_IMAGE_NOT_NULL = "J110002";
    public static final String LEGAL_PERSON_NO_PICTURE_BACK_IMAGE_NOT_NULL = "J1100003";
    public static final String BUSINESS_LICENSE_PICTURE_IMAGE_NOT_NULL = "J1100004";
    public static final String LEGAL_PERSON_NO_PICTURE_FRONT_IMAGE_NOT_EXISTS = "J1100005";
    public static final String BUSINESS_LICENSE_PICTURE_IMAGE_NOT_EXISTS = "J1100006";
    public static final String LEGAL_PERSON_NO_PICTURE_BACK_IMAGE_NOT_EXISTS = "J1100007";
    public static final String BUSINESS_LICENSE_PICTURE_IMAGE_TYPE_IS_ERROR = "J1100008";
    public static final String LEGAL_PERSON_NO_PICTURE_FRONT_IMAGE_TYPE_IS_ERROR = "J1100009";
    public static final String LEGAL_PERSON_NO_PICTURE_BACK_IMAGE_TYPE_IS_ERROR = "J1100010";
    public static final String MANAGER_PLACE_RENT_CONTRACT_IMAGE_NOT_EXISTS = "J1100011";
    public static final String MANAGER_PLACE_RENT_CONTRACT_IMAGE_TYPE_IS_ERROR = "J1100012";
    public static final String LEGAL_PERSON_CREDIT_REPORT_IMAGE_NOT_EXISTS = "J1100013";
    public static final String LEGAL_PERSON_CREDIT_REPORT_IMAGE_TYPE_IS_ERROR = "J1100014";
    public static final String FIXED_ASSETS_PROVE_IMAGE_NOT_EXISTS = "J1100015";
    public static final String FIXED_ASSETS_PROVE_IMAGE_TYPE_IS_ERROR = "J1100016";
    public static final String PUBLIC_ACCOUNT_FLOW_BILL_IMAGE_NOT_EXISTS = "J1100017";
    public static final String PUBLIC_ACCOUNT_FLOW_BILL_IMAGE_TYPE_IS_ERROR = "J1100018";
    public static final String SOCIAL_SECURITY_RO_PROVIDENT_FUND_IMAGE_NOT_EXISTS = "J1100019";
    public static final String SOCIAL_SECURITY_RO_PROVIDENT_FUND_IMAGE_TYPE_IS_ERROR = "J1100020";
    public static final String COOPERATION_AGREEMENT_IMAGE_NOT_EXISTS = "J1100021";
    public static final String COOPERATION_AGREEMENT_IMAGE_TYPE_IS_ERROR = "J1100022";
    public static final String LEGAL_PERSON_EDUCATION_IMAGE_NOT_EXISTS = "J1100023";
    public static final String LEGAL_PERSON_EDUCATION_IMAGE_TYPE_IS_ERROR = "J1100024";
    public static final String LEGAL_PERSON_POSITIONAL_TITLE_IMAGE_NOT_EXISTS = "J1100025";
    public static final String LEGAL_PERSON_POSITIONAL_TITLE_IMAGE_TYPE_IS_ERROR = "J1100026";
    public static final String LOCALE_CHECKLISTS_IMAGE_NOT_EXISTS = "J1100027";
    public static final String LOCALE_CHECKLISTS_IMAGE_TYPE_IS_ERROR = "J1100028";
    public static final String OTHER_DATE_IMAGE_NOT_EXISTS = "J1100029";
    public static final String OTHER_DATE_IMAGE_TYPE_IS_ERROR = "J1100030";
    public static final String IMG_REF_ID_NOT_NULL = "J1100031";
    public static final String IMG_REF_ID_NEED_NULL = "J1100032";
    public static final String CUSTOMER_COMPANY_IMAGES_NOT_NULL = "J1100033";

    public static final String TRANSFER_ORDER_NAME_NOT_NULL = "J1200001";
    public static final String TRANSFER_ORDER_ID_NOT_NULL = "J1200002";
    public static final String TRANSFER_ORDER_NOT_EXISTS = "J1200003";
    public static final String TRANSFER_ORDER_MODE_NOT_NULL = "J1200004";
    public static final String TRANSFER_ORDER_TYPE_NOT_NULL = "J1200005";
    public static final String TRANSFER_ORDER_PRODUCT_ID_NOT_NULL = "J1200006";
    public static final String TRANSFER_ORDER_PRODUCT_SKU_ID_NOT_NULL = "J1200007";
    public static final String TRANSFER_ORDER_PRODUCT_COUNT_NOT_NULL = "J1200008";
    public static final String TRANSFER_ORDER_PRODUCT_AND_MATERIAL_NOT_NULL = "J1200009";
    public static final String TRANSFER_ORDER_MATERIAL_ID_NOT_NULL = "J1200010";
    public static final String TRANSFER_ORDER_MATERIAL_NO_NOT_NULL = "J1200011";
    public static final String TRANSFER_ORDER_MATERIAL_COUNT_NOT_NULL = "J1200012";
    public static final String TRANSFER_ORDER_NO_NOT_NULL = "J1200013";
    public static final String TRANSFER_ORDER_STATUS_IS_ERROR = "J1200014";
    public static final String TRANSFER_ORDER_PRODUCT_EQUIPMENT_STOCK_NOT_ENOUGH = "J1200015";
    public static final String TRANSFER_ORDER_PRODUCT_EQUIPMENT_NO_NOT_NULL = "J1200016";
    public static final String BULK_MATERIAL_IN_TRANSFER_ORDER_IS_NOT_IDLE = "J1200017";
    public static final String TRANSFER_ORDER_PRODUCT_EQUIPMENT_NO_AND_BULK_MATERIAL_NO_NOT_NULL = "J1200018";
    public static final String USER_CAN_NOT_OPERATION_TRANSFER_ORDER_WAREHOUSE = "J1200019";
    public static final String PRODUCT_EQUIPMENT_AND_USER_NOT_SAME_WAREHOUSE = "J1200020";
    public static final String TRANSFER_ORDER_PRODUCT_NOT_EXISTS_BY_EQUIPMENT_NO = "J1200021";
    public static final String TRANSFER_ORDER_IS_NEW_NOT_NULL = "J1200022";
    public static final String TRANSFER_ORDER_MATERIAL_STOCK_NOT_ENOUGH = "J1200023";
    public static final String PRODUCT_EQUIPMENT_IN_TRANSFER_ORDER_ID_NOT_EXISTS = "J1200024";
    public static final String TRANSFER_ORDER_MODE_IS_NOT_OUT = "J1200025";
    public static final String TRANSFER_ORDER_MATERIAL_NOT_EXISTS = "J1200026";
    public static final String TRANSFER_ORDER_PRODUCT_IS_NEW_NOT_NULL = "J1200027";
    public static final String TRANSFER_ORDER_MATERIAL_COUNT_NOT_ENOUGH = "J1200028";
    public static final String TRANSFER_ORDER_PRODUCT_SKU_ID_CAN_NOT_SAME = "J1200029";
    public static final String TRANSFER_ORDER_MATERIAL_NO_CAN_NOT_SAME = "J1200030";
    public static final String TRANSFER_ORDER_MATERIAL_COUNT_NOT_ZERO = "J1200031";
    public static final String TRANSFER_ORDER_INTO_STATUS_NEED_INIT = "J1200032";
    public static final String TRANSFER_ORDER_OUT_STATUS_NEED_CHOICE_GOODS = "J1200033";
    public static final String TRANSFER_ORDER_OUT_NOT_NULL = "J1200034";

    public static final String ASSEMBLE_ORDER_ID_NOT_NULL = "J1300001";
    public static final String ASSEMBLE_ORDER_MATERIAL_ID_NOT_NULL = "J1300002";
    public static final String ASSEMBLE_ORDER_NOT_EXISTS = "J1300003";
    public static final String ASSEMBLE_ORDER_MATERIAL_NOT_NULL = "J1300004";

    public static final String PEER_ID_NOT_NULL = "J1400001";
    public static final String PEER_NAME_NOT_NULL = "J1400002";
    public static final String PEER_CODE_NOT_NULL = "J1400003";
    public static final String PEER_CODE_EXISTS = "J1400004";
    public static final String PEER_NAME_EXISTS = "J1400005";
    public static final String PEER_NO_NOT_EXISTS = "J1400006";
    public static final String PEER_NOT_EXISTS = "J1400007";
    public static final String PEER_EXISTS = "J1400008";
    public static final String PEER_NO_NOT_NULL = "J1400009";

    public static final String PEER_DEPLOYMENT_ORDER_ID_NOT_NULL = "J1500001";
    public static final String PEER_DEPLOYMENT_ORDER_NO_NOT_NULL = "J1500002";
    public static final String PEER_DEPLOYMENT_ORDER_START_TIME_NOT_NULL = "J1500003";
    public static final String PEER_DEPLOYMENT_ORDER_TOTAL_DISCOUNT_AMOUNT_NOT_NULL = "J1500004";
    public static final String PEER_DEPLOYMENT_ORDER_TAX_RATE_ERROR = "J1500005";
    public static final String PEER_DEPLOYMENT_ORDER_RENT_TIME_LENGTH_NOT_NULL = "J1500006";
    public static final String PEER_DEPLOYMENT_ORDER_TOTAL_PRODUCT_COUNT_NOT_NULL = "J1500007";
    public static final String PEER_DEPLOYMENT_ORDER_TOTAL_MATERIAL_COUNT_NOT_NULL = "J1500008";
    public static final String PEER_DEPLOYMENT_ORDER_UNIT_AMOUNT_NOT_NULL = "J1500009";
    public static final String PEER_DEPLOYMENT_ORDER_UNIT_AMOUNT_IS_MATH  = "J1500010";
    public static final String PEER_DEPLOYMENT_ORDER_COUNT_NOT_NULL  = "J1500011";
    public static final String PEER_DEPLOYMENT_ORDER_ERROR  = "J1500012";
    public static final String PEER_DEPLOYMENT_ORDER_IS_NEW_NOT_NULL  = "J1500013";
    public static final String PEER_DEPLOYMENT_ORDER_NOT_EXISTS  = "J1500014";
    public static final String PEER_DEPLOYMENT_ORDER_STATUS_ERROR  = "J1500015";
    public static final String PEER_DEPLOYMENT_ORDER_PRODUCT_MATERIAL_LIST_NOT_NULL  = "J1500016";
    public static final String PEER_DEPLOYMENT_ORDER_RENT_TYPE_NOT_NULL  = "J1500017";
    public static final String PEER_DEPLOYMENT_ORDER_STATUS_IS_COMMIT  = "J1500018";
    public static final String PEER_DEPLOYMENT_ORDER_DELIVERY_MODE_NOT_NULL  = "J1500019";
    public static final String PEER_DEPLOYMENT_ORDER_CONSIGN_INFO_PHONE_IS_MATH  = "J1500020";
    public static final String PEER_DEPLOYMENT_ORDER_RENT_TYPE_IS_ERROR  = "J1500021";
    public static final String PEER_DEPLOYMENT_ORDER_DELIVERY_MODE_IS_ERROR  = "J1500022";
    public static final String PEER_DEPLOYMENT_ORDER_TIME_LENGTH_IS_ZERO  = "J1500023";
    public static final String PEER_DEPLOYMENT_ORDER_START_TIME_DATE_IS_ERROR  = "J1500024";
    public static final String PEER_DEPLOYMENT_ORDER_MONEY_IS_ERROR  = "J1500025";
    public static final String PEER_DEPLOYMENT_ORDER_COUNT_IS_ZERO  = "J1500026";
    public static final String PEER_DEPLOYMENT_ORDER_MONEY_IS_ZERO  = "J1500027";
    public static final String PEER_DEPLOYMENT_ORDER_DISCOUNT_MONEY_IS_ZERO  = "J1500028";
    public static final String PEER_DEPLOYMENT_ORDER_PRODUCT_ID_NOT_NULL  = "J1500029";
    public static final String PEER_DEPLOYMENT_ORDER_STATUS_NEED_CONFIRM  = "J1500030";
    public static final String USER_CAN_NOT_OPERATION_PEER_DEPLOYMENT_ORDER_WAREHOUSE  = "J1500031";
    public static final String PEER_DEPLOYMENT_ORDER_STATUS_NEED_PROCESSING_OUT  = "J1500032";
    public static final String BANK_NO_ERROR  = "J1500033";
    public static final String PRODUCT_EQUIPMENT_MATCH_PEER_DEPLOYMENT_ORDER_NOT_ENOUGH  = "J1500034";

    public static final String CORRECT_AMOUNT_GREATER_THAN_REALITY_AMOUNT = "J1600001";
    public static final String STATEMENT_ORDER_CORRECT_NOT_EXISTS = "J1600002";
    public static final String STATEMENT_ORDER_CORRECT_STATUS_NOT_PENDING = "J1600003";
    public static final String STATEMENT_ORDER_CORRECT_STATUS_NOT_PENDING_OR_COMMIT = "J1600004";
    public static final String STATEMENT_ORDER_ID_NOT_NULL = "J1600005";
    public static final String STATEMENT_ORDER_CORRECT_AMOUNT_NOT_NULL = "J1600006";
    public static final String STATEMENT_ORDER_CORRECT_NO_NOT_NULL = "J1600007";
    public static final String STATEMENT_ORDER_DETAIL_ID_NOT_NULL = "J1600008";
    public static final String STATEMENT_ORDER_DETAIL_NOT_EXISTS = "J1600009";
    public static final String STATEMENT_ORDER_ID_UNEQUAL_TO_STATEMENT_ORDER_DETAIL_ID = "J1600010";
    public static final String STATEMENT_ORDER_CORRECT_EXISTS = "J1600002";
    static {
        MAP.put(SUCCESS, "成功");
        MAP.put(ID_NOT_NULL, "ID不能为空");
        MAP.put(BUSINESS_EXCEPTION, "业务异常");
        MAP.put(SYSTEM_EXCEPTION, "系统异常");
        MAP.put(SYSTEM_ERROR, "系统错误,请联系管理员");
        MAP.put(RECORD_NOT_EXISTS, "记录不存在");
        MAP.put(RECORD_ALREADY_EXISTS, "记录已经存在");
        MAP.put(SYSTEM_DEVELOPING, "开发中……");
        MAP.put(EMAIL_ERROR, "邮箱格式有误");
        MAP.put(DATA_NOT_BELONG_TO_YOU, "数据不属于你，无法操作！");
        MAP.put(DATA_HAVE_NO_PERMISSION, "您没有权限这么做！");
        MAP.put(START_TIME_NOT_NULL, "起始时间不能为空");
        MAP.put(END_TIME_NOT_NULL, "结束时间不能为空");
        MAP.put(COMMITTED_CAN_NOT_REPEAT, "重复提交！");
        MAP.put(COMMIT_ONLY_SELF, "只能提交自己的数据");
        MAP.put(RECORD_USED_CAN_NOT_DELETE, "数据被使用，无法删除");
        MAP.put(AMOUNT_MAST_MORE_THEN_ZERO, "金额必须大于0");
        MAP.put(PHONE_ERROR, "手机号码格式有误");
        MAP.put(BUSINESS_APP_ID_NOT_NULL, "业务系统appId不能为空");
        MAP.put(BUSINESS_APP_SECRET_NOT_NULL, "业务系统appSecret不能为空");
        MAP.put(BUSINESS_SYSTEM_ERROR, "业务系统验证失败");

        MAP.put(USER_NOT_LOGIN, "用户未登录");
        MAP.put(USER_DISABLE, "用户已禁用，请联系管理员");
        MAP.put(USER_NAME_NOT_FOUND, "用户名不存在");
        MAP.put(USER_NOT_ACTIVATED, "用户未激活，请联系管理员");
        MAP.put(USER_PASSWORD_ERROR, "密码错误");
        MAP.put(USER_EXISTS, "用户已存在");
        MAP.put(USER_NAME_NOT_NULL, "用户名不能为空");
        MAP.put(USER_PASSWORD_NOT_NULL, "密码不能为空");
        MAP.put(USER_ROLE_NOT_NULL, "用户角色不能为空");
        MAP.put(ROLE_NOT_NULL, "角色不存在");
        MAP.put(USER_NOT_EXISTS, "用户不存在");
        MAP.put(ROLE_ID_NOT_NULL, "角色ID不能为空");
        MAP.put(DEPARTMENT_ID_NOT_NULL, "部门ID不能为空");
        MAP.put(DEPARTMENT_NOT_NULL, "部门不能为空");
        MAP.put(USER_NOT_NULL, "用户不能为空");
        MAP.put(ACTIVE_USER_ID_NOT_NULL, "观察者用户ID不能为空");
        MAP.put(OPERATOR_IS_NOT_YOURSELF, "操作者不是本人，不能操作");
        MAP.put(ROLE_NAME_NOT_NULL, "角色名称不能为空");
        MAP.put(ROLE_HAVE_USER, "角色包含用户");
        MAP.put(SUB_COMPANY_NAME_NOT_NULL, "子公司名称不能为空");
        MAP.put(DEPARTMENT_NOT_EXISTS, "部门不存在");
        MAP.put(USER_PASSWORD_TOO_SIMPLE, "密码包含大写字母、小写字母、数字、特殊符号中的至少三类，且长度在8到20之间");
        MAP.put(USER_OLD_PASSWORD_NOT_NULL, "旧密码不能为空");
        MAP.put(USER_NEW_PASSWORD_NOT_NULL, "新密码不能为空");
        MAP.put(USER_OWNER_NOT_EXISTS, "不存在填写的开发员，请查询清楚");
        MAP.put(USER_UNION_NOT_EXISTS, "不存在填写的联合开发员，请查询清楚");

        MAP.put(PRODUCT_ID_NOT_NULL, "商品唯一标识不能为空");
        MAP.put(PRODUCT_NAME_NOT_NULL, "商品名称不能为空");
        MAP.put(PRODUCT_PROPERTY_NOT_NULL, "商品属性不能为空");
        MAP.put(PRODUCT_SKU_NOT_NULL, "商品SKU不能为空");
        MAP.put(PRODUCT_SKU_PROPERTY_NOT_NULL, "商品SKU属性不能为空");
        MAP.put(PRODUCT_PROPERTY_VALUE_NOT_NULL, "商品属性值不能为空");
        MAP.put(PRODUCT_SKU_PROPERTY_VALUE_NOT_NULL, "商品SKU属性值不能为空");
        MAP.put(PRODUCT_IMAGE_UPLOAD_ERROR, "商品图片上传失败");
        MAP.put(PRODUCT_IS_NULL_OR_NOT_EXISTS, "商品不存在或发生变更");
        MAP.put(PRODUCT_SKU_IS_NULL_OR_NOT_EXISTS, "商品SKU不存在或发生变更");
        MAP.put(PRODUCT_SKU_PRICE_ERROR, "商品SKU价格填写不正确");
        MAP.put(PRODUCT_SKU_COUNT_ERROR, "商品SKU数量填写不正确");
        MAP.put(PRODUCT_CATEGORY_PROPERTY_NOT_EXISTS, "商品属性不存在");
        MAP.put(PRODUCT_CATEGORY_PROPERTY_VALUE_NOT_EXISTS, "商品属性值不存在");
        MAP.put(PRODUCT_CATEGORY_PROPERTY_VALUE_ALREADY_EXISTS, "商品属性值不存在");
        MAP.put(PRODUCT_EQUIPMENT_NOT_EXISTS, "编号【%s 】的设备不存在");
        MAP.put(MATERIAL_NOT_EXISTS, "配件不存在");
        MAP.put(PRODUCT_EQUIPMENT_HAVE_NO_BULK_MATERIAL, "该设备没有散料，数据有误");
        MAP.put(PRODUCT_EQUIPMENT_IS_NOT_IDLE, "编号【%s 】的设备不在闲置中");
        MAP.put(BULK_MATERIAL_IS_IN_PRODUCT_EQUIPMENT, "散料在某设备上");
        MAP.put(BULK_MATERIAL_NOT_EXISTS, "编号【%s 】的配件不存在");
        MAP.put(PRODUCT_NOT_EXISTS, "商品【%s 】不存在");
        MAP.put(PRODUCT_EQUIPMENT_NOT_IN_THIS_WAREHOUSE, "编号【%s 】的设备不在【%s 】库房中");
        MAP.put(PRODUCT_IS_NOT_RENT, "该商品已下架");
        MAP.put(MATERIAL_IN_USED, "配件正在被使用");
        MAP.put(PRODUCT_SKU_CAN_NOT_DELETE, "检测到您要删除商品SKU，目前SKU不支持删除。");
        MAP.put(BULK_MATERIAL_IS_NOT_IDLE, "编号【%s 】没有在闲置状态。");
        MAP.put(PRODUCT_EQUIPMENT_STATUS_ERROR, "商品设备状态有误。");
        MAP.put(BULK_MATERIAL_STATUS_ERROR, "编号【%s 】散料状态有误。");
        MAP.put(BULK_MATERIAL_NOT_IN_THIS_WAREHOUSE, "散料不在该库房。");
        MAP.put(PRODUCT_MATERIAL_NOT_MATCHING, "商品【%s】配件不匹配。");
        MAP.put(PRODUCT_MATERIAL_MEMORY_NOT_MATCHING, "商品【内存】配件不匹配");
        MAP.put(PRODUCT_MATERIAL_MAIN_BOARD_NOT_MATCHING, "商品【主板】配件不匹配");
        MAP.put(PRODUCT_MATERIAL_CPU_NOT_MATCHING, "商品【CPU】配件不匹配");
        MAP.put(PRODUCT_MATERIAL_HDD_NOT_MATCHING, "商品【机械硬盘】配件不匹配");
        MAP.put(PRODUCT_MATERIAL_GRAPHICS_CARD_NOT_MATCHING, "商品【显卡】配件不匹配");
        MAP.put(PRODUCT_MATERIAL_POWER_SUPPLY_NOT_MATCHING, "商品【电源】配件不匹配");
        MAP.put(PRODUCT_MATERIAL_RADIATOR_NOT_MATCHING, "商品【散热器】配件不匹配");
        MAP.put(PRODUCT_MATERIAL_SSD_NOT_MATCHING, "商品【固态硬盘】配件不匹配");
        MAP.put(PRODUCT_MATERIAL_BOX_NOT_MATCHING, "商品【机箱】配件不匹配");
        MAP.put(PRODUCT_EQUIPMENT_IS_NOT_BUSY, "编号【%s 】的设备不在租赁中");
        MAP.put(BULK_MATERIAL_IS_NOT_BUSY, "编号【%s 】的配件不在租赁中");
        MAP.put(BULK_MATERIAL_IS_IN_ORDER_EQUIPMENT, "编号【%s 】在某订单或者某设备上");
        MAP.put(BULK_MATERIAL_HAVE_NOT_ENOUGH, "配件库存不足！");
        MAP.put(BULK_MATERIAL_ID_NOT_NULL, "散料ID不能为空！");
        MAP.put(PRODUCT_EQUIPMENT_MATERIAL_COUNT_NOT_ENOUGH, "该设备的此种配件不足");
        MAP.put(PRODUCT_EQUIPMENT_BULK_MATERIAL_NOT_EXISTS, "该设备的此种散料不存在");
        MAP.put(CURRENT_EQUIPMENT_ID_NOT_NULL, "当前设备的id不能为空");
        MAP.put(CURRENT_EQUIPMENT_NO_NOT_NULL, "当前设备的编号不能为空");
        MAP.put(BULK_MATERIAL_IS_IN_PRODUCT_EQUIPMENT_NOT_REPAIR, "编号【%s 】的散料在某设备上，不能进行维修");
        MAP.put(BULK_MATERIAL_IS_NOT_IN_PRODUCT_EQUIPMENT, "散料不在某设备上");
        MAP.put(INSTALL_AND_DISMANTLE_WAREHOUSE_NOT_EQUAL, "安装的散料和拆卸的散料不是同一个仓库");
        MAP.put(PRODUCT_EQUIPMENT_MATERIAL_NOT_EXISTS, "编号【%s 】的设备配件不存在");
        MAP.put(BULK_MATERIAL_IS_NULL, "该散料不存在");
        MAP.put(PRODUCT_EQUIPMENT_IS_NULL, "该设备不存在");
        MAP.put(PRODUCT_EQUIPMENT_MATERIAL_IS_NULL, "该设备配件不存在");
        MAP.put(BULK_MATERIAL_NO_NOT_NULL, "散料编号不能为空");
        MAP.put(PRODUCT_EQUIPMENT_NOT_SAME_WAREHOUSE, "编号【%s 】的设备与其他设备不在同一仓库");
        MAP.put(BULK_MATERIAL_NOT_SAME_WAREHOUSE, "编号【%s 】的散料与其他散料不在同一仓库");
        MAP.put(PRODUCT_EQUIPMENT_AND_BULK_MATERIAL_NOT_SAME_WAREHOUSE, "设备和散料不在同一仓库");
        MAP.put(PRODUCT_EQUIPMENT_STATUS_NOT_REPAIR, "编号【%s 】的设备只有处于设备空闲或者租赁中,才能进行新增维修操作");
        MAP.put(BULK_MATERIAL_STATUS_NOT_REPAIR, "编号【%s 】的散料只有处于设备空闲或者租赁中,才能进行新增维修操作");
        MAP.put(PRODUCT_NOT_SAME, "收货商品不一致");
        MAP.put(MATERIAL_NOT_SAME, "收货配件不一致");
        MAP.put(CUSTOMER_COMPANY_NEED_SKU_ID_NOT_NULL, "企业客户首次所需设备的sku的ID不能为空");
        MAP.put(CUSTOMER_COMPANY_NEED_UNIT_PRICE_NOT_NULL, "企业客户首次所需设备的单台价值不能空");
        MAP.put(CUSTOMER_COMPANY_NEED_RENT_COUNT_NOT_NULL, "企业客户首次所需设备的租赁数量不能空");
        MAP.put(CUSTOMER_COMPANY_NEED_RENT_LENGHT_NOT_NULL, "企业客户首次所需设备的租赁期限不能空");
        MAP.put(CUSTOMER_COMPANY_NEED_FIRST_NOT_NULL, "企业客户首次所需设备选项不能空");
        MAP.put(ORDER_MATERIAL_STOCK_NEW_INSUFFICIENT, "全新配件库存不足！");
        MAP.put(ORDER_MATERIAL_STOCK_OLD_INSUFFICIENT, "次新配件库存不足！");
        MAP.put(ORDER_PRODUCT_COUNT_ERROR, "商品数量必须大于0！");
        MAP.put(ORDER_MATERIAL_COUNT_ERROR, "设备数量必须大于0！");
        MAP.put(CUSTOMER_RENT_THIS_BULK_MATERIAL_NO_MORE, "该配件客户的在租只有【%d】个！");
        MAP.put(ORDER_PRODUCT_EQUIPMENT_NOT_MATCHING, "订单设备不匹配");
        MAP.put(WAREHOUSE_NOT_AVAILABLE, "您无权使用该仓库");
        MAP.put(PRODUCT_EQUIPMENT_NOT_NEW, "设备不是全新的");
        MAP.put(PRODUCT_EQUIPMENT_NOT_OLD, "设备不是次新的");
        MAP.put(DEPLOYMENT_ORDER_HAVE_NO_THIS_PRODUCT_EQUIPMENT, "调拨单没有该设备");
        MAP.put(DEPLOYMENT_ORDER_BULK_MATERIAL_NOT_ENOUGH, "调拨单配件不足");
        MAP.put(DEPLOYMENT_ORDER_NOT_EXISTS, "调拨单不存在");
        MAP.put(DEPLOYMENT_ORDER_PRODUCT_EQUIPMENT_HAVE_RETURNED, "调拨单该设备已经退还");
        MAP.put(PURCHASE_APPLY_ORDER_NO_NOT_NULL, "采购申请单编号不能为空");
        MAP.put(PURCHASE_APPLY_ORDER_NOT_EXISTS, "采购申请单不存在");
        MAP.put(BULK_MATERIAL_HAVE_NOT_ENOUGH_BY_PARAM, "配件【%s】库存不足！");
        MAP.put(PURCHASE_APPLY_CAN_NOT_UPDATE, "此状态采购申请单不可修改");
        MAP.put(PURCHASE_APPLY_CAN_NOT_CANCEL_BY_STATUS, "此状态采购申请单不可取消");
        MAP.put(PURCHASE_APPLY_YET_RECEIVE_CAN_NOT_CANCEL, "已收货的采购申请单不可取消");
        MAP.put(CUSTOMER_OWNER_NOT_NULL, "客户业务员ID不能为空");
        MAP.put(PURCHASE_APPLY_USE_TIME_NOT_NUll, "计划使用时间不能为空");
        MAP.put(STATEMENT_ORDER_CAN_NOT_PAID_THIS, "历史有未结算的结算单，不能支付该项");
        MAP.put(WORKFLOW_TYPE_NOT_EXISTS, "工作流类型不存在");
        MAP.put(WORKFLOW_TEMPLATE_HAVE_NO_NODE, "此工作流模板没有节点");
        MAP.put(WORKFLOW_LINK_EXISTS, "此单工作流已经存在");
        MAP.put(WORKFLOW_LINK_NOT_EXISTS, "此单工作流不存在");
        MAP.put(WORKFLOW_LINK_HAVE_NO_DETAIL, "此单工作流没有明细");
        MAP.put(WORKFLOW_LINK_VERIFY_ALREADY_OVER, "此单工作流已经结束");
        MAP.put(WORKFLOW_NOT_BELONG_TO_YOU, "此单工作流还不该您审核");
        MAP.put(WORKFLOW_NOT_EXISTS_CLOSED, "此工作流不存在或已经关闭");
        MAP.put(WORKFLOW_NODE_NOT_EXISTS, "此工作流节点不存在");
        MAP.put(WORKFLOW_VERIFY_USER_ERROR, "此工作流审核人员有误");
        MAP.put(WORKFLOW_LINK_STATUS_ERROR, "此工作流状态有误");
        MAP.put(WORKFLOW_TEMPLATE_NOT_EXISTS, "工作流模板不存在或者已经禁用");
        MAP.put(WORKFLOW_HAVE_NO_CONFIG, "审核工作流没有配置");
        MAP.put(CUSTOMER_RISK_MANAGEMENT_APPLE_LIMIT, "苹果设备被限制，不能下单");
        MAP.put(CUSTOMER_RISK_MANAGEMENT_NEW_LIMIT, "全新设备被限制，不能下单");
        MAP.put(CUSTOMER_RISK_MANAGEMENT_PRICE_LIMIT, "价格被限制，不能下单");
        MAP.put(CUSTOMER_STATUS_ERROR, "客户状态异常，仔细检查后操作");
        MAP.put(CUSTOMER_IS_DISABLED, "客户已经被禁用");
        MAP.put(CUSTOMER_CAN_NOT_EDIT, "客户在该状态下不允许修改");
        MAP.put(PURCHASE_APPLY_CAN_NOT_PAUSE, "此采购申请单不能暂停");
        MAP.put(PURCHASE_APPLY_CAN_NOT_CONTINUE, "此采购申请单不能恢复暂停");
        MAP.put(PURCHASE_APPLY_CAN_NOT_END, "此采购申请单不能结束");
        MAP.put(PURCHASE_NOT_HAVE_APPLY, "采购计划中没有【%s】");
        MAP.put(ORDER_RENT_LENGTH_MORE_THAN_90, "订单租期不允许");
        MAP.put(BULK_MATERIAL_NOT_IN_THE_WAREHOUSE, "编号【%s 】的散料不在【%s 】库房中");
        MAP.put(PRODUCT_NEW_SKU_PRICE_IS_NOT_NULL, "全新商品本身的价值不能为空");
        MAP.put(PRODUCT_NEW_DAY_RENT_PRICE_IS_NOT_NULL, "全新天租赁价格不能为空");
        MAP.put(PRODUCT_NEW_MONTH_RENT_PRICE_IS_NOT_NULL, "全新月租赁价格不能为空");
        MAP.put(ORDER_PRODUCT_EQUIPMENT_NEW_NOT_MATCHING, "订单设备项目的新旧属性不匹配。");
        MAP.put(RETURN_TIME_NOT_NULL, "退还时间不能为空");
        MAP.put(RETURN_REASON_TYPE_NOT_NULL, "退换原因不能为空");
        MAP.put(ORDER_EXPECT_DELIVERY_TIME_ERROR, "预计发货时间必须在租赁时间之前，并且不能大于2天");
        MAP.put(ORDER_NO_NOT_NULL, "订单号不能为空");
        MAP.put(BUYER_CUSTOMER_NO_NOT_NULL, "购买人编号不能为空");

        MAP.put(REMARK_PATTERN, "备注信息超过限制，最多输入200个字符");
        MAP.put(ID_NOT_NULL, "ID不能为空");
        MAP.put(MONEY_MORE_THAN_ZERO, "金额不能小于0");
        MAP.put(IMAGE_NOT_EXISTS, "图片不存在");
        MAP.put(IMAGE_TYPE_ERROR, "图片类型错误");
        MAP.put(IMAGE_USED, "图片已使用");
        MAP.put(DATA_DICTIONARY_NAME_NOT_NULL, "系统字典名称不能为空");
        MAP.put(PARAM_IS_NOT_NULL, "参数不能为空");
        MAP.put(HAVE_NO_CHANGE_STATUS, "无需改变状态");
        MAP.put(STATUS_PATTERN, "未知状态");
        MAP.put(COUNT_MORE_THAN_ZERO, "数量必须大于0");
        MAP.put(DAYS_MORE_THAN_ZERO, "天数不能小于0");
        MAP.put(DATA_STATUS_ERROR, "数据状态异常");
        MAP.put(VERIFY_STATUS_ERROR, "审核状态异常");
        MAP.put(OPERATOR_IS_NOT_YOURSELF, "操作者不是本人，不能操作");
        MAP.put(PARAM_IS_NOT_ENOUGH, "信息不全，请仔细检查");
        MAP.put(NO_DUPLICATE_COMMIT, "禁止重复提交");
        MAP.put(PARAM_IS_ERROR, "参数有误，请仔细检查");

        MAP.put(PURCHASE_ORDER_ID_NOT_NULL, "采购订单ID不能为空");
        MAP.put(PRODUCT_SUPPLIER_ID_NOT_NULL, "商品供应商ID不能为空");
        MAP.put(WAREHOUSE_ID_NOT_NULL, "仓库ID不能为空");
        MAP.put(IS_INVOICE_NOT_NULL, "是否有发票字段必填");
        MAP.put(IS_NEW_NOT_NULL, "是否是全新机字段必填");
        MAP.put(PURCHASE_ORDER_PRODUCT_LIST_NOT_NULL, "采购订单商品项列表不能为空");
        MAP.put(IS_INVOICE_VALUE_ERROR, "是否有发票参数错误");
        MAP.put(IS_NEW_VALUE_ERROR, "是否是全新机参数错误");
        MAP.put(PURCHASE_ORDER_NO_NOT_NULL, "采购订单号不能为空");
        MAP.put(PURCHASE_ORDER_NOT_EXISTS, "采购订单不存在");
        MAP.put(PURCHASE_ORDER_COMMITTED_CAN_NOT_UPDATE, "待审核状态的采购单不允许修改");
        MAP.put(PURCHASE_ORDER_CANNOT_CREATE_BY_NEW_AND_AMOUNT, "分公司采购全新机不能大于两万元");
        MAP.put(WAREHOUSE_NOT_EXISTS, "仓库不存在");
        MAP.put(PURCHASE_ORDER_PRODUCT_CAN_NOT_REPEAT, "采购订单项重复");
        MAP.put(PURCHASE_ORDER_COMMITTED_CAN_NOT_COMMIT_AGAIN, "已提交的采购单不能再次提交");
        MAP.put(WAREHOUSE_IN_STORAGE_LIST_NOT_NULL, "商品入仓数据不能为空");
        MAP.put(WAREHOUSE_OUT_STORAGE_LIST_NOT_NULL, "商品出仓数据不能为空");
        MAP.put(USER_CAN_NOT_OP_WAREHOUSE, "您没有该仓库的操作权限");
        MAP.put(VERIFY_USER_NOT_NULL, "审核人不能为空");
        MAP.put(PURCHASE_ORDER_COMMITTED_CAN_NOT_CANCEL, "已提交的采购单不能取消");
        MAP.put(PURCHASE_DELIVERY_ORDER_NO_NOT_NULL, "采购发货单编号不能为空");
        MAP.put(PURCHASE_DELIVERY_ORDER_NOT_EXISTS, "采购发货单不存在");
        MAP.put(WAREHOUSE_NO_NOT_NULL, "仓库编号不能为空");
        MAP.put(SUPPLIER_NOT_EXISTS, "供应商不存在");
        MAP.put(PURCHASE_RECEIVE_ORDER_NO_NOT_NULL, "采购收货单编号不能为空");
        MAP.put(PURCHASE_RECEIVE_ORDER_NOT_EXISTS, "采购收货单不存在");
        MAP.put(PURCHASE_RECEIVE_ORDER_AUTO_ALLOT_YES_CAN_NOT_UPDATE, "自动流转到总仓的采购发货单不能修改");
        MAP.put(PURCHASE_RECEIVE_ORDER_STATUS_CAN_NOT_UPDATE, "此采购收货单不能修改");
        MAP.put(PURCHASE_RECEIVE_ORDER_PRODUCT_LIST_NOT_NULL, "采购收货单商品项列表不能为空");
        MAP.put(PURCHASE_RECEIVE_ORDER_PRODUCT_REAL_COUNT_NOT_NULL, "商品SKU实际数量填写不正确");
        MAP.put(PURCHASE_RECEIVE_ORDER_PRODUCT_SKU_ID_NOT_NULL, "采购收货单商品项商品SKU_ID不能为空");
        MAP.put(STOCK_ORDER_ALREADY_EXISTS, "入库单已经存在，不能入库");
        MAP.put(PURCHASE_ORDER_STATUS_CAN_NOT_END, "当前采购单状态不允许结束");
        MAP.put(PURCHASE_ORDER_STATUS_CAN_NOT_CONTINUE, "当前采购单状态不允许继续采购");
        MAP.put(PURCHASE_RECEIVE_ORDER_STATUS_YET_CAN_NOT_IN_AGAIN, "已入库的采购收货单不允许再次入库");
        MAP.put(PURCHASE_TYPE_ERROR, "采购单类型错误");
        MAP.put(PURCHASE_TYPE_NOT_NULL, "采购单类型不能为空");
        MAP.put(PURCHASE_PRODUCT_MATERIAL_CAN_NOT_ALL_NULL, "采购单商品项和配件项不能都为空");
        MAP.put(MATERIAL_ID_NOT_NULL, "配件ID不能为空");
        MAP.put(MATERIAL_PRICE_ERROR, "配件价格填写不正确");
        MAP.put(MATERIAL_COUNT_ERROR, "配件数量填写不正确");
        MAP.put(PURCHASE_ORDER_MATERIAL_CAN_NOT_REPEAT, "采购单配件项不能重复");
        MAP.put(PURCHASE_ORDER_MATERIAL_NOT_MAIN, "采购单配件项存在非四大件");
        MAP.put(PURCHASE_ORDER_MATERIAL_NOT_GADGET, "采购单配件项存在非小配件");
        MAP.put(PURCHASE_ORDER_MATERIAL_LIST_NOT_NULL, "采购订单配件项列表不能为空");
        MAP.put(PURCHASE_ORDER_MATERIAL_CAN_NOT_CREATE, "采购小配件总金额大于100元必须有发票");
        MAP.put(PURCHASE_ORDER_SKU_MATERIAL_ERROR, "SKU配件配置错误");
        MAP.put(MATERIAL_NO_NOT_NULL, "配件编号不能为空");
        MAP.put(STOCK_ALLOCATION_WAREHOUSE_IS_NOT_SAME, "库存调拨库房必须是同一间");
        MAP.put(PURCHASE_RECEIVE_ORDER_MATERIAL_ID_NOT_NULL, "采购收货单配件项配件ID不能为空");
        MAP.put(PURCHASE_RECEIVE_ORDER_MATERIAL_REAL_COUNT_NOT_NULL, "采购收货单配件项实际配件数量不能为空");
        MAP.put(MATERIAL_CAPACITY_VALUE_NOT_NULL, "配件字面量不能为空");
        MAP.put(MATERIAL_MODEL_NOT_NULL, "配件型号不能为空");
        MAP.put(MATERIAL_TYPE_HAVE_NO_MODEL, "该配件类型没有型号");
        MAP.put(PURCHASE_RECEIVE_ORDER_MATERIAL_NO_NOT_NULL, "采购收货单配件项配件编号不能为空");
        MAP.put(CUSTOMER_CONSIGN_NOT_EXISTS, "客户收货地址不存在");
        MAP.put(CUSTOMER_GET_CREDIT_AMOUNT_OVER_FLOW, "客户授信额度超限");
        MAP.put(CUSTOMER_GET_CREDIT_NEED_RISK_INFO, "客户需要授信额度，未检测到风控信息");
        MAP.put(STATEMENT_PAY_TYPE_ERROR, "结算单支付方式有误");
        MAP.put(STATEMENT_PAY_FAILED, "结算单支付失败");
        MAP.put(STATEMENT_PAY_AMOUNT_DIFF_ERROR, "您上次有支付记录正在处理中，请联系业务员手动关闭或者等待2小时再来支付！");
        MAP.put(STOCK_NOT_MATCH, "备货不匹配");
        MAP.put(STOCK_NOT_ENOUGH, "备货不足，请先继续备货");
        MAP.put(MATERIAL_NOT_RENT, "不是客户在租配件，不能退还");
        MAP.put(EQUIPMENT_PURCHASE_PRICE_NOT_NULL, "编号为【%s】的设备没有填写价格，请确保所有设备及配件填写了采购价");
        MAP.put(BULK_PURCHASE_PRICE_NOT_NULL, "编号为【%s】的配件没有填写价格，请确保所有设备及配件填写了采购价");
        MAP.put(PURCHASE_PRICE_ERROR, "采购价格填写错误");
        MAP.put(PURCHASE_RECEIVE_ORDER_STATUS_YET_CAN_NOT_COMMIT, "此采购收货单不能提交");
        MAP.put(PURCHASE_RECEIVE_ORDER_MATERIAL_PRICE_NOT_NEED_UPDATE, "此采购单配件价格无需修改");
        MAP.put(UPDATE_ITEM_COUNT_ERROR, "修改的配件数量不匹配");
        MAP.put(SUB_COMPANY_NOT_EXISTS, "分公司不存在");
        MAP.put(COMPANY_ORIGIN_NOT_NULL, "客户来源不能为空");
        MAP.put(PERSON_NAME_NOT_NULL, "个人客户的用户名不能为空");
        MAP.put(PERSON_NO_NOT_NULL, "个人客户的身份证号不能为空");
        MAP.put(CUSTOMER_PERSON_CONNECT_REAL_NAME_NOT_NULL, "个人客户紧急联系人姓名不能为空");
        MAP.put(CUSTOMER_PERSON_CONNECT_PHONE_NOT_NULL, "个人客户紧急联系人电话不能为空");
        MAP.put(PRODUCT_PURPOSE_NOT_NULL, "设备用途不能为空");
        MAP.put(LIST_FIRST_NEED_PRODUCTS_NOT_NULL, "首次所需设备不能为空");
        MAP.put(SALES_MAN_NOT_NULL, "业务员不能为空");
        MAP.put(PURCHASE_TAX_RATE_ERROR, "采购单税率有误");
        MAP.put(CUSTOMER_COMPANY_NEED_FIRST_LIST_NOT_NULL, "首次所需设备不能为空");
        MAP.put(CUSTOMER_IS_EXISTS, "客户已经存在");
        MAP.put(SUPPLIER_IS_EXISTS, "供应商已经存在");
        MAP.put(SUPPLIER_NAME_IS_NULL, "供应商名字有空格");
        MAP.put(MUST_HAVE_MAIN, "含有小配件的整机四大件采购单必须有整机");
        MAP.put(SUPPLIER_NAME_NOT_NULL, "供应商名字不能为空");
        MAP.put(SUPPLIER_CODE_NOT_CN, "自定义编码只能输入英文和数字和（下及中画线符号）");
        MAP.put(SUPPLIER_CODE_IS_LENGTH, "自定义编码长度超过20");
        MAP.put(BENEFICIARY_BANK_NAME_IS_LENGTH, "收款开户行长度超过100");
        MAP.put(BENEFICIARY_NAME_IS_LENGTH, "收款户名长度超过100");
        MAP.put(BENEFICIARY_ACCOUNT_IS_MATH, "收款帐号只能数字和（-）");
        MAP.put(BENEFICIARY_ACCOUNT_IS_LENGTH, "收款帐号长度不能超过30");
        MAP.put(SUPPLIER_CODE_IS_EXISTS, "自定义供应商编号已经存在");
        MAP.put(SHORT_LIMIT_RECEIVABLE_AMOUNT_NOT_NULL, "客户的短期应收上限金额不能为空");
        MAP.put(CUSTOMER_OWNER_NOT_CHANGE_ELECTRIC_SALE_COMPANY, "客户的开发人员不能由地方分公司转为电销人员");
        MAP.put(CUSTOMER_UNION_USER_NOT_CHANGE_ELECTRIC_SALE_COMPANY, "客户的联合开发员不能由地方分公司转为电销人员");
        MAP.put(CUSTOMER_OWNER_IS_NOT_HEADER_COMPANY, "客户的开发员不能为总公司人员");
        MAP.put(CUSTOMER_UNION_USER_IS_NOT_HEADER_COMPANY, "客户的联合开发员不能为总公司人员");
        MAP.put(STATEMENT_DATE_NOT_NULL, "客户的结算时间不能为空");
        MAP.put(CUSTOMER_OWNER_USER_AND_UNION_USER_NOT_SAME, "客户的开发员和联合开发员不能同一个人");
        MAP.put(CUSTOMER_IS_DEFAULT_CONSIGN_ADDRESS_NOT_NULL, "客户是否将详细地址作为收货地址的该选项不能为空");
        MAP.put(CUSTOMER_CONSIGN_ADDRESS_NOT_NULL, "客户的收货地址的不能为空");
        MAP.put(CUSTOMER_COMPANY_NEED_TOTAL_PRICE_NOT_NULL, "企业客户首次所需设备的总价值不能空");
        MAP.put(CUSTOMER_COMPANY_INDUSTRY_NOT_NULL, "企业客户的所属行业不能为空");
        MAP.put(CUSTOMER_COMPANY_FOUND_TIME_NOT_NULL, "企业客户的企业成立时间不能为空");
        MAP.put(CUSTOMER_COMPANY_REGISTERED_CAPITAL_NOT_NULL, "企业客户的注册资本不能为空");
        MAP.put(CUSTOMER_COMPANY_OFFICE_NUMBER_NOT_NULL, "企业客户的办公人数不能为空");
        MAP.put(CUSTOMER_COMPANY_OPERATING_AREA_NOT_NULL, "企业客户的经营面积不能为空");
        MAP.put(LEGAL_PERSON_PHONE_EQUAL_TO_AGENT_PERSON_PHONE, "法人手机号与经办人电话相同");
        MAP.put(AGENT_PERSON_PHONE_EQUAL_TO_CONNECT_PHONE, "经办人电话与紧急联系人手机号相同");
        MAP.put(CONNECT_PHONE_EQUAL_TO_LEGAL_PERSON_PHONE, "紧急联系人手机号与法人手机号相同");

        MAP.put(ORDER_PRODUCT_LIST_NOT_NULL, "订单商品不能为空");
        MAP.put(ORDER_CUSTOMER_CONSIGN_NOT_NULL, "订单没有选择地址");
        MAP.put(ORDER_PRODUCT_STOCK_NEW_INSUFFICIENT, "全新商品库存不足");
        MAP.put(ORDER_PRODUCT_STOCK_OLD_INSUFFICIENT, "次新商品库存不足");
        MAP.put(ORDER_NOT_EXISTS, "订单不存在");
        MAP.put(ORDER_PRODUCT_EQUIPMENT_NOT_NULL, "订单商品项设备编号不能为空");
        MAP.put(ORDER_PRODUCT_EQUIPMENT_STATUS_ERROR, "该设备不存在或者该设备状态异常，请仔细检查");
        MAP.put(ORDER_PRODUCT_EQUIPMENT_SKU_NOT_SAME, "该用户购买的商品不是这个型号的，请仔细检查");
        MAP.put(ORDER_PRODUCT_EQUIPMENT_IS_NULL, "订单商品项设备编号为空");
        MAP.put(ORDER_STATUS_ERROR, "订单状态不正确，请仔细检查");
        MAP.put(ORDER_PRODUCT_EQUIPMENT_COUNT_ERROR, "订单商品设备数不正确，请仔细检查");
        MAP.put(ORDER_PRODUCT_BULK_MATERIAL_COUNT_ERROR, "订单配件数不正确，请仔细检查");
        MAP.put(ORDER_RENT_TYPE_OR_LENGTH_ERROR, "订单租赁方式或时长有误");
        MAP.put(ORDER_PAY_MODE_NOT_NULL, "订单支付方式不能为空");
        MAP.put(ORDER_PAY_STATUS_ERROR, "付款单状态异常，请检查");
        MAP.put(ORDER_REFUND_STATUS_ERROR, "退款单状态异常，请检查");
        MAP.put(ORDER_PAY_RECORD_NOT_EXISTS, "支付记录不存在");
        MAP.put(ORDER_HAVE_NO_RENT_START_TIME, "订单没有租赁开始时间");
        MAP.put(DEPLOYMENT_ORDER_PRODUCT_EQUIPMENT_STOCK_NOT_ENOUGH, "货物调拨该库房该商品库存不足。");
        MAP.put(DEPLOYMENT_ORDER_BULK_MATERIAL_STOCK_NOT_ENOUGH, "货物调拨该库房该配件库存不足。");
        MAP.put(DEPLOYMENT_ORDER_STATUS_ERROR, "调配单状态有误。");
        MAP.put(DEPLOYMENT_ORDER_HAVE_NO_THIS_ITEM, "编号【%s 】不在该调拨单项中。");
        MAP.put(ORDER_STATUS_NOT_PROCESSED, "订单还没处理完。");
        MAP.put(ORDER_PRODUCT_AMOUNT_ERROR, "订单商品价格有误。");
        MAP.put(ORDER_MATERIAL_AMOUNT_ERROR, "订单配件价格有误。");
        MAP.put(ORDER_HAVE_NO_THIS_ITEM, "编号【%s 】不在该订单项中或者新旧属性不匹配，请仔细检查。");
        MAP.put(ORDER_PRODUCT_EQUIPMENT_COUNT_MAX, "设备数超过了订单项最大数：%d");
        MAP.put(ORDER_MATERIAL_BULK_COUNT_MAX, "配件数超过了订单项最大数：%d ");
        MAP.put(DEPLOYMENT_ORDER_PRODUCT_EQUIPMENT_COUNT_MAX, "设备数超过了调拨单项最大数：%d。");
        MAP.put(DEPLOYMENT_ORDER_MATERIAL_BULK_COUNT_MAX, "配件数超过了调拨单项最大数：%d");
        MAP.put(DEPLOYMENT_ORDER_WAREHOUSE_NOT_SAME, "调拨单仓库不能为同一个。");
        MAP.put(DEPLOYMENT_ORDER_HAVE_LOCK_ITEM, "调拨单有锁定的商品或配件，请仔细检查。");
        MAP.put(DEPLOYMENT_ORDER_PRODUCT_EQUIPMENT_COUNT_NOT_ENOUGH, "调拨单商品备货不足");
        MAP.put(DEPLOYMENT_ORDER_MATERIAL_BULK_COUNT_NOT_ENOUGH, "调拨单配件备货不足");
        MAP.put(RETURN_ORDER_PRODUCT_ID_NOT_NULL, "退还单商品项不能为空");
        MAP.put(RETURN_ORDER_MATERIAL_ID_NOT_NULL, "退还单配件项不能为空");
        MAP.put(RETURN_ORDER_SERVICE_COST_NOT_NULL, "服务费不能为空");
        MAP.put(RETURN_ORDER_SERVICE_COST_ERROR, "服务费金额有误");
        MAP.put(RETURN_ORDER_DAMAGE_COST_NOT_NULL, "损坏费用不能为空");
        MAP.put(RETURN_ORDER_DAMAGE_COST_ERROR, "损坏费用金额有误");
        MAP.put(ORDER_HAVE_NO_PAID, "订单未支付，不能操作");
        MAP.put(ORDER_CAN_NOT_DELIVERY, "订单不能发货");
        MAP.put(ORDER_PAY_MODE_ERROR, "您当前不支持这种支付方式。");
        MAP.put(CHANGE_COUNT_ERROR, "更换数量错误");
        MAP.put(CHANGE_ORDER_NO_NOT_NULL, "换货单编号不能为空");
        MAP.put(CHANGE_ORDER_NOT_EXISTS, "换货单不存在");
        MAP.put(CHANGE_ORDER_COMMITTED_CAN_NOT_COMMIT_AGAIN, "只有待提交状态的换货单可以提交");
        MAP.put(CHANGE_ORDER_STATUS_CAN_NOT_STOCK_UP, "换货单审核通过后才可备货");
        MAP.put(CHANGE_ORDER_CAN_NOT_UPDATE, "当前换货单不允许修改");
        MAP.put(CHANGE_ORDER_PRODUCT_ID_NOT_NULL, "换货商品项ID不能为空");
        MAP.put(CHANGE_ORDER_MATERIAL_ID_NOT_NULL, "换货配件项ID不能为空");
        MAP.put(CHANGE_ORDER_STATUS_CAN_NOT_DELIVERY, "不是备货中的换货单不能发货");
        MAP.put(CHANGE_ORDER_STATUS_CAN_NOT_END, "不是处理中的换货单不允许结束");
        MAP.put(ORDER_PRODUCT_EQUIPMENT_NOT_EXISTS, "该设备不在该订单里，请仔细检查");
        MAP.put(ORDER_PRODUCT_EQUIPMENT_ALREADY_RETURN, "订单设备已经归还");
        MAP.put(CHANGE_ORDER_STATUS_CAN_NOT_CANCEL, "此状态的换货单换货单不允许取消");
        MAP.put(CHANGE_ORDER_STATUS_CAN_NOT_DO_CHANGE, "当前换货单不允许进行换货操作");
        MAP.put(CHANGE_ONLY_SAME_SKU, "目前仅支持更换相同SKU设备");
        MAP.put(ORDER_ALREADY_PAID, "订单已经支付");
        MAP.put(ORDER_MATERIAL_BULK_NOT_EXISTS, "散料不在该订单里，请仔细检查");
        MAP.put(ORDER_MATERIAL_BULK_ALREADY_RETURN, "订单散料已经归还了");
        MAP.put(CHANGE_ORDER_SRC_EQUIPMENT_NO_NOT_NULL, "原设备编号不能为空");
        MAP.put(CHANGE_ORDER_CAN_NOT_CHANGE, "此商品在本换货单中无法换货，您可尝试取消本退还单后，重新生成SKU相符的换货单，或进行退货再租操作");
        MAP.put(CHANGE_ORDER_SRC_MATERIAL_NO_NOT_NULL, "原配件编号不能为空");
        MAP.put(CHANGE_ORDER_MATERIAL_CAN_NOT_MODIFY, "此换货单配件项回库数已不可修改");
        MAP.put(CHANGE_ORDER_NOT_END, "此换货单尚有未处理完成的设备");
        MAP.put(ORDER_MATERIAL_STOCK_INSUFFICIENT, "订单配件项库存不足");
        MAP.put(ORDER_PRODUCT_LIST_REPEAT, "订单商品项重复");
        MAP.put(ORDER_MATERIAL_LIST_REPEAT, "订单配件项重复");
        MAP.put(RETURN_OR_CHANGE_MODE_NOT_NULL, "退换方式不能为空");
        MAP.put(RETURN_OR_CHANGE_MODE_ERROR, "退换方式错误");
        MAP.put(RETURN_ORDER_CAN_NOT_UPDATE, "只有未提交审核的退还单可以修改");
        MAP.put(IS_DAMAGE_NOT_NULL, "是否损坏字段必填");
        MAP.put(IS_DAMAGE_ERROR, "是否损坏字段错误");
        MAP.put(RETURN_ORDER_CAN_NOT_COMMIT, "只有待提交的退还单可以提交审核");
        MAP.put(ORDER_PRODUCT_NOT_EXISTS, "商品订单项不存在");
        MAP.put(ORDER_MATERIAL_NOT_EXISTS, "商品配件项不存在");
        MAP.put(ORDER_PRODUCT_DEPOSIT_ERROR, "订单商品押金有误，需为商品价格的倍数");
        MAP.put(ORDER_MATERIAL_DEPOSIT_ERROR, "订单配件押金有误，需为配件价格的倍数");
        MAP.put(ORDER_DELIVERY_MODE_ERROR, "订单送货方式有误，请仔细检查");
        MAP.put(ORDER_CAN_NOT_DELIVERY_TIME_REASON, "订单未到发货时间，不能发货");


        MAP.put(CUSTOMER_COMPANY_NOT_NULL, "企业客户信息不能为空");
        MAP.put(CUSTOMER_COMPANY_NAME_NOT_NULL, "企业公司名称不能为空");
        MAP.put(CUSTOMER_PERSON_NOT_NULL, "客户个人信息不能为空");
        MAP.put(CUSTOMER_PERSON_NAME_NOT_NULL, "客户个人姓名不能为空");
        MAP.put(CUSTOMER_TYPE_NOT_NULL, "客户类型不能为空");
        MAP.put(CUSTOMER_COMPANY_CONNECT_NAME_NOT_NULL, "企业客户联系人姓名不能为空");
        MAP.put(CUSTOMER_NOT_NULL, "客户不存在");
        MAP.put(CUSTOMER_NO_NOT_NULL, "客户编号不能为空");
        MAP.put(CUSTOMER_RISK_MANAGEMENT_ID_NOT_NULL, "风控ID不能为空");
        MAP.put(CUSTOMER_RISK_MANAGEMENT_CREDIT_AMOUNT_NOT_NULL, "授信额度不能为空");
        MAP.put(CUSTOMER_RISK_MANAGEMENT_DEPOSIT_CYCLE_NOT_NULL, "押金期数不能为空");
        MAP.put(CUSTOMER_RISK_MANAGEMENT_PAYMENT_CYCLE_NOT_NULL, "付款期数不能为空");
        MAP.put(CUSTOMER_NOT_EXISTS, "客户不存在");
        MAP.put(CUSTOMER_RISK_MANAGEMENT_CREDIT_AMOUNT_ERROR, "授信额度最小为0，最大为10000000");
        MAP.put(CUSTOMER_RISK_MANAGEMENT_DEPOSIT_CYCLE_ERROR, "押金期数最小为0，最大为120");
        MAP.put(CUSTOMER_RISK_MANAGEMENT_PAYMENT_CYCLE_ERROR, "付款期数最小为1，最大为120");
        MAP.put(CUSTOMER_RISK_MANAGEMENT_NOT_EXISTS, "风控信息不存在");
        MAP.put(CUSTOMER_HAVE_NO_RETURN, "客户没有可归还商品");
        MAP.put(CUSTOMER_NOT_RENT_THIS, "客户没有租赁该商品");
        MAP.put(CUSTOMER_RETURN_TOO_MORE, "客户退换商品数超过限制");
        MAP.put(CONSIGNEE_NAME_NOT_NULL, "收货人姓名不能为空");
        MAP.put(CONSIGNEE_PHONE_NOT_NULL, "收货人电话不能为空");
        MAP.put(PROVINCE_ID_NOT_NULL, "省份ID不能为空");
        MAP.put(CITY_ID_NOT_NULL, "城市ID不能为空");
        MAP.put(DISTRICT_ID_NOT_NULL, "街道ID不能为空");
        MAP.put(ADDRESS_NOT_NULL, "地址不能为空");
        MAP.put(RETURN_COUNT_ERROR, "退还数量必须大于0");
        MAP.put(RETURN_ORDER_NO_NOT_NULL, "退还单号不能为空");
        MAP.put(EQUIPMENT_NO_NOT_NULL, "设备编号不能为空");
        MAP.put(RETURN_ORDER_NOT_EXISTS, "退还单不存在");
        MAP.put(EQUIPMENT_NOT_EXISTS, "设备不存在");
        MAP.put(EQUIPMENT_NOT_RENT, "该设备不是客户在租设备，不能退还");
        MAP.put(RETURN_ORDER_IS_CHARGING_IS_NOT_NULL, "是否计租赁费用不能为空");
        MAP.put(PRODUCT_SKU_CAN_NOT_REPEAT, "SKU不能重复");
        MAP.put(MATERIAL_CAN_NOT_REPEAT, "配件不能重复");
        MAP.put(RETURN_ORDER_STATUS_CAN_NOT_END, "只有处理中的退还单可以结束");
        MAP.put(RETURN_ORDER_STATUS_CAN_NOT_CANCEL, "只有待处理的退还单可以取消");
        MAP.put(RETURN_ORDER_STATUS_CAN_NOT_RETURN, "此退还单状态不允许退货");
        MAP.put(CUSTOMER_CONSIGN_INFO_NOT_EXISTS, "收货地址信息不存在");
        MAP.put(CUSTOMER_CONSIGN_INFO_IS_MAIN_NOT_NULL, "是否是默认地址字段必填");
        MAP.put(CUSTOMER_CONSIGN_INFO_IS_MAIN_ERROR, "是否是默认地址填写错误");
        MAP.put(CUSTOMER_CONSIGN_INFO_ID_NOT_NULL, "收货地址信息ID不能为空");
        MAP.put(CUSTOMER_COMPANY_CONNECT_PHONE_NOT_NULL, "企业客户联系人电话不能为空");
        MAP.put(CUSTOMER_COMPANY_ADDRESS_NOT_NULL, "企业客户详细地址不能为空");
        MAP.put(CUSTOMER_PERSON_PHONE_NOT_NULL, "个人客户联系电话不能为空");
        MAP.put(CUSTOMER_PERSON_ADDRESS_NOT_NULL, "个人客户详细地址不能为空");
        MAP.put(STATEMENT_ORDER_CREATE_ERROR, "结算单生成失败");
        MAP.put(STATEMENT_ORDER_STATUS_ERROR, "结算单状态异常");
        MAP.put(STATEMENT_ORDER_NO_NOT_NULL, "结算单编号不能为空");
        MAP.put(STATEMENT_PAY_NOT_NULL, "结算单支付方式不能为空");
        MAP.put(OPEN_ID_NOT_NULL, "公众唯一标识不能为空");
        MAP.put(CUSTOMER_NAME_NOT_NULL, "客户名称不能为空");
        MAP.put(STATEMENT_ORDER_NOT_EXISTS, "结算单不存在");
        MAP.put(STATEMENT_ORDER_NOT_NULL, "月份结算单不能为空");

        MAP.put(MESSAGE_TITLE_NOT_NULL, "站内信标题不能为空");
        MAP.put(MESSAGE_CONTENT_NOT_NULL, "站内信内容不能为空");
        MAP.put(MESSAGE_RECEIVER_NOT_NULL, "站内信收件人不能为空");
        MAP.put(MESSAGE_ID_NOT_NULL, "站内信ID不能为空");
        MAP.put(MESSAGE_NOT_EXISTS, "站内信不存在");
        MAP.put(MESSAGE_CAN_NOT_SEND_SELF, "站内信不能发给自己");

        MAP.put(EQUIPMENT_AND_BULK_MATERIAL_IS_NOT_NULL, "设备维修单明细表不能为空");
        MAP.put(REPAIR_REASON_IS_NOT_NULL, "设备维修单的维修原因不能为空");
        MAP.put(REPAIR_ORDER_NO_IS_NOT_NULL, "设备维修单编号不能为空");
        MAP.put(REPAIR_ORDER_IS_NOT_EXISTS, "设备维修单不存在");
        MAP.put(REPAIR_ORDER_STATUS_ERROR, "设备维修单状态出错，请重新检查");
        MAP.put(REPAIR_ORDER_EQUIPMENT_NOT_EXISTS, "设备维修单明细不存在");
        MAP.put(REPAIR_ORDER_BULK_MATERRIAL_NOT_EXISTS, "散料维修单明细不存在");
        MAP.put(REPAIR_ORDER_DATA_STATUS_ERROR, "该设备维修单此状态不允许此操作");

        MAP.put(JOINT_PRODUCT_ID_IS_NULL, "组合商品id为空");
        MAP.put(JOINT_PRODUCT_NAME_IS_NULL, "组合商品名称为空");
        MAP.put(JOINT_PRODUCT_NOT_EXISTS, "组合商品不存在");

        MAP.put(IMG_ID_NOT_NULL, "传入的图片的ID不能为空");
        MAP.put(LEGAL_PERSON_NO_PICTURE_FRONT_IMAGE_NOT_NULL, "法人/股东身份证正面照片不能为空");
        MAP.put(LEGAL_PERSON_NO_PICTURE_BACK_IMAGE_NOT_NULL, "法人/股东身份证反面照片不能为空");
        MAP.put(BUSINESS_LICENSE_PICTURE_IMAGE_NOT_NULL, "企业营业执照不能为空");
        MAP.put(LEGAL_PERSON_NO_PICTURE_FRONT_IMAGE_NOT_EXISTS, "法人/股东身份证正面照片不存在");
        MAP.put(LEGAL_PERSON_NO_PICTURE_BACK_IMAGE_NOT_EXISTS, "法人/股东身份证反面照片不存在");
        MAP.put(BUSINESS_LICENSE_PICTURE_IMAGE_NOT_EXISTS, "企业营业执照照片不存在");
        MAP.put(BUSINESS_LICENSE_PICTURE_IMAGE_TYPE_IS_ERROR, "传入的不是营业执照照片，请重新传入");
        MAP.put(LEGAL_PERSON_NO_PICTURE_FRONT_IMAGE_TYPE_IS_ERROR, "传入的并不是身份证正面照片，请重新传入");
        MAP.put(LEGAL_PERSON_NO_PICTURE_BACK_IMAGE_TYPE_IS_ERROR, "传入的并不是身份证反面照片，请重新传入");
        MAP.put(MANAGER_PLACE_RENT_CONTRACT_IMAGE_NOT_EXISTS, "经营场所租赁合同不存在");
        MAP.put(MANAGER_PLACE_RENT_CONTRACT_IMAGE_TYPE_IS_ERROR, "传入的不是经营场所租赁合同照片，请重新传入");
        MAP.put(LEGAL_PERSON_CREDIT_REPORT_IMAGE_NOT_EXISTS, "法人个人征信报告或附（法人个人征信授权书）照片不存在");
        MAP.put(LEGAL_PERSON_CREDIT_REPORT_IMAGE_TYPE_IS_ERROR, "传入的不是法人个人征信报告或附（法人个人征信授权书）照片，请重新传入");
        MAP.put(FIXED_ASSETS_PROVE_IMAGE_NOT_EXISTS, "固定资产证明照片不存在");
        MAP.put(FIXED_ASSETS_PROVE_IMAGE_TYPE_IS_ERROR, "传入的不是固定资产证明照片，请重新传入");
        MAP.put(PUBLIC_ACCOUNT_FLOW_BILL_IMAGE_NOT_EXISTS, "单位对公账户流水账单照片不存在");
        MAP.put(PUBLIC_ACCOUNT_FLOW_BILL_IMAGE_TYPE_IS_ERROR, "传入的不是单位对公账户流水账单照片，请重新传入");
        MAP.put(SOCIAL_SECURITY_RO_PROVIDENT_FUND_IMAGE_NOT_EXISTS, "社保/公积金缴纳证明照片不存在");
        MAP.put(SOCIAL_SECURITY_RO_PROVIDENT_FUND_IMAGE_TYPE_IS_ERROR, "传入的不是社保/公积金缴纳证明照片，请重新传入");
        MAP.put(COOPERATION_AGREEMENT_IMAGE_NOT_EXISTS, "战略协议或合作协议照片不存在");
        MAP.put(COOPERATION_AGREEMENT_IMAGE_TYPE_IS_ERROR, "传入的不是战略协议或合作协议照片，请重新传入");
        MAP.put(LEGAL_PERSON_EDUCATION_IMAGE_NOT_EXISTS, "法人学历证明照片不存在");
        MAP.put(LEGAL_PERSON_EDUCATION_IMAGE_TYPE_IS_ERROR, "传入的不是法人学历证明照片，请重新传入");
        MAP.put(LEGAL_PERSON_POSITIONAL_TITLE_IMAGE_NOT_EXISTS, "法人职称证明照片不存在");
        MAP.put(LEGAL_PERSON_POSITIONAL_TITLE_IMAGE_TYPE_IS_ERROR, "传入的不是法人职称证明照片，请重新传入");
        MAP.put(LOCALE_CHECKLISTS_IMAGE_NOT_EXISTS, "现场核查表照片不存在");
        MAP.put(LOCALE_CHECKLISTS_IMAGE_TYPE_IS_ERROR, "传入的不是现场核查表照片，请重新传入");
        MAP.put(OTHER_DATE_IMAGE_NOT_EXISTS, "其他材料的照片不存在");
        MAP.put(OTHER_DATE_IMAGE_TYPE_IS_ERROR, "传入的不是其他材料的照片，请重新传入");
        MAP.put(IMG_REF_ID_NOT_NULL, "图片的ref-ID不能为空");
        MAP.put(IMG_REF_ID_NEED_NULL, "编号【%s 】的图片refID已经有值，不能进行该操作");
        MAP.put(CUSTOMER_COMPANY_IMAGES_NOT_NULL, "企业客户的营业执照和法人/股东身份证正反面图片，在提交审核时不能为空");

        MAP.put(TRANSFER_ORDER_NAME_NOT_NULL, "转移单名称不能为空");
        MAP.put(TRANSFER_ORDER_ID_NOT_NULL, "转移单ID不能为空");
        MAP.put(TRANSFER_ORDER_NOT_EXISTS, "转移单不存在");
        MAP.put(TRANSFER_ORDER_MODE_NOT_NULL, "转移单方式不能为空");
        MAP.put(TRANSFER_ORDER_TYPE_NOT_NULL, "转移单类型不能为空");
        MAP.put(TRANSFER_ORDER_PRODUCT_ID_NOT_NULL, "转移单商品ID不能为空");
        MAP.put(TRANSFER_ORDER_PRODUCT_SKU_ID_NOT_NULL, "转移单商品SKU ID不能为空");
        MAP.put(TRANSFER_ORDER_PRODUCT_COUNT_NOT_NULL, "转移单物料数量不能为空");
        MAP.put(TRANSFER_ORDER_PRODUCT_AND_MATERIAL_NOT_NULL, "转移单商品和物料不能同时为空");
        MAP.put(TRANSFER_ORDER_MATERIAL_ID_NOT_NULL, "转移单物料ID不能为空");
        MAP.put(TRANSFER_ORDER_MATERIAL_NO_NOT_NULL, "转移单物料编号不能为空");
        MAP.put(TRANSFER_ORDER_MATERIAL_COUNT_NOT_NULL, "转移单物料数量不能为空");
        MAP.put(TRANSFER_ORDER_NO_NOT_NULL, "转移单编号不能为空");
        MAP.put(TRANSFER_ORDER_STATUS_IS_ERROR, "转移单状态有误");
        MAP.put(TRANSFER_ORDER_PRODUCT_EQUIPMENT_STOCK_NOT_ENOUGH, "货物转移该仓库该商品库存不足。");
        MAP.put(TRANSFER_ORDER_MATERIAL_STOCK_NOT_ENOUGH, "货物转移该仓库该物料库存不足。");
        MAP.put(TRANSFER_ORDER_PRODUCT_EQUIPMENT_NO_AND_BULK_MATERIAL_NO_NOT_NULL, "转移单商品设备编号和物转移单散料编号不能同时为空。");
        MAP.put(USER_CAN_NOT_OPERATION_TRANSFER_ORDER_WAREHOUSE, "该用户不能操作这个仓库下的转移单。");
        MAP.put(PRODUCT_EQUIPMENT_AND_USER_NOT_SAME_WAREHOUSE, "编号【%s 】的设备与用户不在同一个仓库");
        MAP.put(TRANSFER_ORDER_PRODUCT_NOT_EXISTS_BY_EQUIPMENT_NO, "编号【%s 】的设备对应的转移单商品表不存在");
        MAP.put(TRANSFER_ORDER_IS_NEW_NOT_NULL, "转移单配件表下的散料全新字段不能为空");
        MAP.put(PRODUCT_EQUIPMENT_IN_TRANSFER_ORDER_ID_NOT_EXISTS, "该设备并不在此转移单中");
        MAP.put(TRANSFER_ORDER_MODE_IS_NOT_OUT, "该转移单不是转出类型");
        MAP.put(TRANSFER_ORDER_MATERIAL_NOT_EXISTS, "转移单配件表不存在");
        MAP.put(TRANSFER_ORDER_PRODUCT_EQUIPMENT_NO_NOT_NULL, "转移单下的商品设备编号不能为空");
        MAP.put(BULK_MATERIAL_IN_TRANSFER_ORDER_IS_NOT_IDLE, "该物料下的散料有不处于空闲状态，不能进行转移操作");
        MAP.put(TRANSFER_ORDER_PRODUCT_IS_NEW_NOT_NULL, "转移单商品表下的商品设备全新字段不能为空");
        MAP.put(TRANSFER_ORDER_MATERIAL_COUNT_NOT_ENOUGH, "该转移单配件表需要清货的物料数量不足");
        MAP.put(TRANSFER_ORDER_PRODUCT_SKU_ID_CAN_NOT_SAME, "不允许传入重复的商品skuID和全新选项");
        MAP.put(TRANSFER_ORDER_MATERIAL_NO_CAN_NOT_SAME, "不允许传入重复的物料编号和全新选项");
        MAP.put(TRANSFER_ORDER_MATERIAL_COUNT_NOT_ZERO, "配件清货时转移单物料数量不能为0");
        MAP.put(TRANSFER_ORDER_INTO_STATUS_NEED_INIT, "提交的转入单状态必须为初始化");
        MAP.put(TRANSFER_ORDER_OUT_STATUS_NEED_CHOICE_GOODS, "提交的转出单状态必须为配货中");
        MAP.put(TRANSFER_ORDER_OUT_NOT_NULL, "转出单不能提交设备列表和散料列表同时为空的数据");


        MAP.put(ASSEMBLE_ORDER_ID_NOT_NULL, "组装单ID不能为空");
        MAP.put(ASSEMBLE_ORDER_NOT_EXISTS, "组装单不存在");
        MAP.put(ASSEMBLE_ORDER_MATERIAL_ID_NOT_NULL, "组装单配件ID不能为空");
        MAP.put(ASSEMBLE_ORDER_MATERIAL_NOT_NULL, "组装单配件不能为空");

        MAP.put(PEER_ID_NOT_NULL, "同行唯一标识不能为空");
        MAP.put(PEER_NAME_NOT_NULL, "同行供应商名称不能为空");
        MAP.put(PEER_CODE_NOT_NULL, "同行供应商自定义编码不能为空");
        MAP.put(PEER_NAME_EXISTS, "同行供应商名称已存在");
        MAP.put(PEER_CODE_EXISTS, "同行供应商自定义编码已存在");
        MAP.put(PEER_EXISTS, "同行供应商编码已存在");
        MAP.put(PEER_NOT_EXISTS, "同行供应不存在");
        MAP.put(PEER_NO_NOT_EXISTS, "同行供应商编码不存在");
        MAP.put(PEER_NO_NOT_NULL, "同行供应商编码不能为空");

        MAP.put(PEER_DEPLOYMENT_ORDER_ID_NOT_NULL, "同行调拨单唯一标识不能为空");
        MAP.put(PEER_DEPLOYMENT_ORDER_NO_NOT_NULL, "同行调拨单编号不能为空");
        MAP.put(PEER_DEPLOYMENT_ORDER_START_TIME_NOT_NULL, "同行调拨单起租时间不能为空");
        MAP.put(PEER_DEPLOYMENT_ORDER_TOTAL_DISCOUNT_AMOUNT_NOT_NULL, "同行调拨单优惠金额不能为空");
        MAP.put(PEER_DEPLOYMENT_ORDER_TAX_RATE_ERROR, "同行调拨单税率有误");
        MAP.put(PEER_DEPLOYMENT_ORDER_RENT_TIME_LENGTH_NOT_NULL, "同行调拨单租赁期限不能为空");
        MAP.put(PEER_DEPLOYMENT_ORDER_TOTAL_PRODUCT_COUNT_NOT_NULL, "同行调拨单商品总数不能为空");
        MAP.put(PEER_DEPLOYMENT_ORDER_TOTAL_MATERIAL_COUNT_NOT_NULL, "同行调拨单配件总数不能为空");
        MAP.put(PEER_DEPLOYMENT_ORDER_UNIT_AMOUNT_NOT_NULL, "同行调拨单单价不能为空");
        MAP.put(PEER_DEPLOYMENT_ORDER_UNIT_AMOUNT_IS_MATH, "同行调拨单单价只能输入数字");
        MAP.put(PEER_DEPLOYMENT_ORDER_COUNT_NOT_NULL, "同行调拨单数量不能为空");
        MAP.put(PEER_DEPLOYMENT_ORDER_ERROR, "同行调拨单数量格式错误");
        MAP.put(PEER_DEPLOYMENT_ORDER_IS_NEW_NOT_NULL, "同行调拨单全新或次新不能为空");
        MAP.put(PEER_DEPLOYMENT_ORDER_NOT_EXISTS, "同行调拨单不存在");
        MAP.put(PEER_DEPLOYMENT_ORDER_STATUS_ERROR, "同行调拨单状态有误");
        MAP.put(PEER_DEPLOYMENT_ORDER_PRODUCT_MATERIAL_LIST_NOT_NULL, "同行调拨单商品和配件不能全空");
        MAP.put(PEER_DEPLOYMENT_ORDER_RENT_TYPE_NOT_NULL, "同行调拨单租赁方式不能为空");
        MAP.put(PEER_DEPLOYMENT_ORDER_STATUS_IS_COMMIT, "同行调拨单只能未提交状态进行修改");
        MAP.put(PEER_DEPLOYMENT_ORDER_PRODUCT_ID_NOT_NULL, "同行调拨单货物调拨商品项ID不能为空");
        MAP.put(PEER_DEPLOYMENT_ORDER_DELIVERY_MODE_NOT_NULL, "同行调拨单发货方式不能为空");
        MAP.put(PEER_DEPLOYMENT_ORDER_STATUS_NEED_CONFIRM, "同行调拨单只有确认收货状态，才能进行归还审核");
        MAP.put(USER_CAN_NOT_OPERATION_PEER_DEPLOYMENT_ORDER_WAREHOUSE, "该用户不能操作这个仓库下的同行调拨单。");
        MAP.put(PEER_DEPLOYMENT_ORDER_CONSIGN_INFO_PHONE_IS_MATH, "同行调拨收货信息单手机号只能輸入数字");
        MAP.put(PEER_DEPLOYMENT_ORDER_RENT_TYPE_IS_ERROR, "同行调拨单租赁方式只能选天租和月租");
        MAP.put(PEER_DEPLOYMENT_ORDER_DELIVERY_MODE_IS_ERROR, "同行调拨单发货方式只能快递和自提");
        MAP.put(PEER_DEPLOYMENT_ORDER_STATUS_NEED_PROCESSING_OUT, "只有状态为退回处理中的同行调拨单才能进行此操作");
        MAP.put(BANK_NO_ERROR, "银行卡号不正确");
        MAP.put(PEER_DEPLOYMENT_ORDER_TIME_LENGTH_IS_ZERO, "同行调拨单租赁期限必须大于0");
        MAP.put(PEER_DEPLOYMENT_ORDER_START_TIME_DATE_IS_ERROR, "同行调拨单起时间必须大于等于当天");
        MAP.put(PEER_DEPLOYMENT_ORDER_MONEY_IS_ERROR, "同行调拨单优惠金额大过订单金额");
        MAP.put(PEER_DEPLOYMENT_ORDER_COUNT_IS_ZERO, "同行调拨单配件和商品总数需大于等于0");
        MAP.put(PEER_DEPLOYMENT_ORDER_MONEY_IS_ZERO, "同行调拨单配件和商品金额需大于等于0");
        MAP.put(PEER_DEPLOYMENT_ORDER_DISCOUNT_MONEY_IS_ZERO, "同行调拨单优惠金额需大于等于0");
        MAP.put(PRODUCT_EQUIPMENT_MATCH_PEER_DEPLOYMENT_ORDER_NOT_ENOUGH, "查找到的设备数量与该同行调拨单下设备数量不相等");

        MAP.put(CORRECT_AMOUNT_GREATER_THAN_REALITY_AMOUNT, "冲正金额大于实际金额");
        MAP.put(STATEMENT_ORDER_CORRECT_NOT_EXISTS, "结算冲正单不存在");
        MAP.put(STATEMENT_ORDER_CORRECT_STATUS_NOT_PENDING, "结算单不是待提交状态");
        MAP.put(STATEMENT_ORDER_CORRECT_STATUS_NOT_PENDING_OR_COMMIT, "结算单不是待提交状态或者提交状态");
        MAP.put(STATEMENT_ORDER_ID_NOT_NULL, "结算单ID不能为空");
        MAP.put(STATEMENT_ORDER_CORRECT_AMOUNT_NOT_NULL, "冲正金额不能为空");
        MAP.put(STATEMENT_ORDER_CORRECT_NO_NOT_NULL, "冲正单号不能为空");
        MAP.put(STATEMENT_ORDER_DETAIL_ID_NOT_NULL, "结算单项ID不能为空");
        MAP.put(STATEMENT_ORDER_DETAIL_NOT_EXISTS, "结算单明细记录不存在");
        MAP.put(STATEMENT_ORDER_ID_UNEQUAL_TO_STATEMENT_ORDER_DETAIL_ID, "结算单ID不对应结算单项ID");
        MAP.put(STATEMENT_ORDER_CORRECT_EXISTS, "结算冲正单已存在");

    }

    public static String getMessage(String code) {
        return MAP.get(code);
    }

    public static String getMessage(String code, String parmName) {
        return MAP.get(code) + " : " + parmName;
    }

    public static String clear(String code) {
        return MAP.put(code, "");
    }
}
